"""Stage 9: hostile review of the decomposition.

Every check below is written to *fail* the diagnosis, not to confirm it.  Each
recomputes a quantity from a different starting point than the stage that
produced it, so a shared bug has to survive two independent routes to go
undetected.

Lens 1  Denominator closure -- the three taxonomies must partition their
        endpoint populations exactly, with no case invented, dropped, or double
        counted, and must agree with the frozen case manifest.
Lens 2  Seal fidelity -- every recomputed A1 status, cross-seed selection count
        and representative must equal the sealed value.
Lens 3  Endpoint arithmetic -- G1/G2/G3 counts recomputed from the CSVs alone
        must reproduce the restored analysis, including its Wilson bounds.
Lens 4  Attribution exclusivity -- each case carries exactly one root-cause
        class, and the per-class counts must sum to the denominator.
Lens 5  Safety -- an independent scan for any structurally accepted expression
        with non-mass support anywhere in the G3 population, computed without
        the G3 classifiers.
Lens 6  Counterfactual honesty -- the control arm of every counterfactual must
        reproduce the frozen rule exactly; a counterfactual whose control arm
        drifts is discarded.
Lens 7  Search-freedom -- no stage may have imported PySR or run a search.
Lens 8  Claim discipline -- assertions the evidence cannot support must be
        absent.  Specifically: no stage may claim a truth-equivalent expression
        was "never generated by the search", because per-seed Pareto fronts are
        not persisted.
"""
from __future__ import annotations

import csv
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from muru_v1_diag_common import (  # noqa: E402
    DIAG_ROOT,
    OUT_DIR,
    eligible_case_ids,
    install_frozen_src,
    load_case_manifest,
    load_restored_analysis,
    load_sealed_records,
    load_seed_records,
    read_json,
    write_json,
)

install_frozen_src()

from muru.paper_benchmark.g2_contract import wilson_lower_95, wilson_upper_95  # noqa: E402

FINDINGS: list[dict] = []


def check(lens: str, name: str, passed: bool, detail: str) -> None:
    FINDINGS.append(
        {"lens": lens, "check": name, "status": "PASS" if passed else "FAIL", "detail": detail}
    )


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def truthy(value: str) -> bool:
    return value == "True"


def main() -> int:
    manifest = load_case_manifest()
    sealed = load_sealed_records()
    restored = load_restored_analysis()

    g1 = read_csv(DIAG_ROOT / "MURU_V1_G1_FAILURE_TAXONOMY.csv")
    g2 = read_csv(DIAG_ROOT / "MURU_V1_G2_FAILURE_TAXONOMY.csv")
    g3 = read_csv(DIAG_ROOT / "MURU_V1_G3_FAILURE_TAXONOMY.csv")

    # ---- Lens 1: denominator closure -------------------------------------
    for label, rows, endpoint, expected in (
        ("G1", g1, "G1", 164),
        ("G2", g2, "G2", 144),
        ("G3", g3, "G3", 36),
    ):
        ids = [r["case_id"] for r in rows]
        eligible = set(eligible_case_ids(endpoint, manifest))
        check(
            "1_denominator",
            f"{label} row count == {expected}",
            len(ids) == expected,
            f"{len(ids)} rows",
        )
        check(
            "1_denominator",
            f"{label} ids unique",
            len(set(ids)) == len(ids),
            f"{len(ids) - len(set(ids))} duplicates",
        )
        check(
            "1_denominator",
            f"{label} ids == frozen manifest eligibility",
            set(ids) == eligible,
            f"symmetric difference {len(set(ids) ^ eligible)}",
        )
        check(
            "1_denominator",
            f"{label} denominator matches restored analysis",
            expected
            == restored["endpoint_denominators"][
                {"G1": "scalar_competence", "G2": "family_recovery", "G3": "principal_structural_safety"}[
                    endpoint
                ]
            ],
            "endpoint_denominators agreement",
        )

    all_ids = {r["case_id"] for r in g1} | {r["case_id"] for r in g2} | {r["case_id"] for r in g3}
    check(
        "1_denominator",
        "union of the three populations is a subset of the 240 Held-out cases",
        all_ids <= set(manifest),
        f"{len(all_ids)} distinct cases covered of 240",
    )

    # ---- Lens 2: seal fidelity -------------------------------------------
    a1 = read_json(OUT_DIR / "a1_decomposition.json")
    check(
        "2_seal_fidelity",
        "A1 recomputation reproduces every sealed a1_case_adequacy_status",
        a1["sealed_status_mismatches"] == 0 and a1["sealed_status_reproduced"] == 240,
        f"{a1['sealed_status_reproduced']}/240 reproduced, "
        f"{a1['sealed_status_mismatches']} mismatches",
    )
    trace = read_json(OUT_DIR / "g2_pipeline_trace.json")
    check(
        "2_seal_fidelity",
        "cross-seed replay reproduces every sealed selection_count and representative",
        trace["cross_seed_replay_reproduced_seal_for"] == 144,
        f"{trace['cross_seed_replay_reproduced_seal_for']}/144",
    )

    # Independent re-derivation of selection_count straight from the seed files.
    seed_records = load_seed_records()
    voting_mismatch = 0
    for row in g2:
        rows_for_case = seed_records[row["case_id"]]
        voting = sum(1 for r in rows_for_case if r["status"] == "COMPLETED_WITH_CANDIDATES")
        if int(row["selection_count_sealed"]) > voting:
            voting_mismatch += 1
    check(
        "2_seal_fidelity",
        "no case claims more votes than it had voting seeds",
        voting_mismatch == 0,
        f"{voting_mismatch} impossible vote counts",
    )

    # ---- Lens 3: endpoint arithmetic -------------------------------------
    g1_successes = sum(1 for r in g1 if truthy(r["g1_success"]))
    g2_successes = sum(1 for r in g2 if truthy(r["g2_success"]))
    g3_violations = sum(1 for r in g3 if truthy(r["is_violation"]))

    check(
        "3_arithmetic",
        "G1 successes recomputed from CSV == restored analysis",
        g1_successes == restored["g1"]["competent"] == 67,
        f"csv {g1_successes} vs restored {restored['g1']['competent']}",
    )
    check(
        "3_arithmetic",
        "G2 successes recomputed from CSV == restored analysis",
        g2_successes == restored["g2"]["successes"] == 4,
        f"csv {g2_successes} vs restored {restored['g2']['successes']}",
    )
    check(
        "3_arithmetic",
        "G3 violations recomputed from CSV == restored analysis",
        g3_violations == restored["g3"]["violations"] == 26,
        f"csv {g3_violations} vs restored {restored['g3']['violations']}",
    )
    check(
        "3_arithmetic",
        "G1 Wilson lower bound reproduces",
        abs(wilson_lower_95(g1_successes, 164) - restored["g1"]["wilson_lower_95"]) < 1e-12,
        f"{wilson_lower_95(g1_successes, 164):.9f}",
    )
    check(
        "3_arithmetic",
        "G2 Wilson lower bound reproduces",
        abs(wilson_lower_95(g2_successes, 144) - restored["g2"]["wilson_lower_95"]) < 1e-12,
        f"{wilson_lower_95(g2_successes, 144):.9f}",
    )
    check(
        "3_arithmetic",
        "G3 Wilson upper bound reproduces",
        abs(wilson_upper_95(g3_violations, 36) - restored["g3"]["wilson_upper_95"]) < 1e-12,
        f"{wilson_upper_95(g3_violations, 36):.9f}",
    )

    # G2 sealed event partition must close.
    events = Counter(r["g2_event_sealed"] for r in g2)
    check(
        "3_arithmetic",
        "G2 SUCCESS + FAILURE + UNEVALUABLE == 144",
        sum(events.values()) == 144
        and events["SUCCESS"] == 4
        and events["FAILURE"] == restored["g2"]["failures"]
        and events["UNEVALUABLE"] == restored["g2"]["unevaluable"],
        dict(events),
    )

    # G1's stage distribution must agree with the restored failure_stage tally.
    a1_rows = {r["case_id"]: r for r in a1["per_case"]}
    boundary_240 = sum(
        1 for r in a1_rows.values() if r["recomputed_a1_status"] == "BOUNDARY_LIMITED"
    )
    check(
        "3_arithmetic",
        "A1-indeterminate case count matches the restored a1_adequacy failure stage",
        boundary_240 == restored["failure_stage_distribution"]["a1_adequacy"] == 154,
        f"{boundary_240} vs {restored['failure_stage_distribution']['a1_adequacy']}",
    )

    # ---- Lens 4: attribution exclusivity ---------------------------------
    for label, rows, expected in (("G1", g1, 164), ("G2", g2, 144), ("G3", g3, 36)):
        classes = Counter(r["root_cause_class"] for r in rows)
        check(
            "4_attribution",
            f"{label} root-cause classes partition the population",
            sum(classes.values()) == expected,
            dict(classes),
        )
        blank = sum(1 for r in rows if not r["root_cause_class"])
        check(
            "4_attribution",
            f"{label} every case carries a root-cause class",
            blank == 0,
            f"{blank} blank",
        )

    # G1: every failure must have m0 among its failing conjuncts, or the
    # "adequacy is the whole G1 gap" claim is wrong.
    g1_failures = [r for r in g1 if not truthy(r["g1_success"])]
    without_m0 = [r for r in g1_failures if "m0_accepted" not in r["failing_conditions"]]
    check(
        "4_attribution",
        "every G1 failure fails the m0_accepted conjunct",
        not without_m0,
        f"{len(without_m0)} failures without m0 in the failing set",
    )
    m0_only = [r for r in g1_failures if r["failing_conditions"] == "m0_accepted"]
    check(
        "4_attribution",
        "G1 failures decompose as 87 m0-only + 10 m0-plus-competence",
        len(m0_only) == 87 and len(g1_failures) == 97,
        f"{len(m0_only)} m0-only of {len(g1_failures)} failures",
    )

    # ---- Lens 5: safety ---------------------------------------------------
    unsafe_direct = []
    for case_id in eligible_case_ids("G3", manifest):
        record = sealed[case_id]
        if record["acceptance_status"] != "STRUCTURAL_ACCEPTED":
            continue
        support = set(record["effective_support"] or [])
        if support - {"mass"}:
            unsafe_direct.append(case_id)
    check(
        "5_safety",
        "no structurally accepted G3 case carries non-mass effective support",
        not unsafe_direct,
        f"{len(unsafe_direct)} unsafe acceptances found by direct scan",
    )
    unsafe_labelled = [r for r in g3 if truthy(r["unsafe_structural_acceptance"])]
    check(
        "5_safety",
        "direct scan and G3 classifier agree that zero unsafe acceptances occurred",
        len(unsafe_labelled) == len(unsafe_direct) == 0,
        f"classifier {len(unsafe_labelled)}, direct scan {len(unsafe_direct)}",
    )
    # Widen the scan past G3: any accepted case anywhere in the 240.
    accepted_anywhere = [
        cid for cid, rec in sealed.items() if rec["acceptance_status"] == "STRUCTURAL_ACCEPTED"
    ]
    check(
        "5_safety",
        "structural acceptance count across all 240 matches the restored analysis",
        len(accepted_anywhere) == restored["structural_accepted_count"] == 25,
        f"{len(accepted_anywhere)} accepted",
    )

    # ---- Lens 6: counterfactual honesty ----------------------------------
    counterfactual = read_json(OUT_DIR / "g2_counterfactuals.json")["summary"]
    check(
        "6_counterfactual",
        "G2 counterfactual control arm reproduces the frozen identity rule",
        counterfactual["arms"]["IDENTITY_frozen_v1"]["successes"]
        == counterfactual["official_v1_g2_successes"]
        == 4,
        f"control arm {counterfactual['arms']['IDENTITY_frozen_v1']['successes']}",
    )
    probe = read_json(OUT_DIR / "boundary_probe_magnitude.json")
    control = probe["a1_status_counts_by_relative_floor"]["0.0"]
    check(
        "6_counterfactual",
        "A1 counterfactual control arm (floor 0.0) reproduces the frozen A1 result",
        control.get("BOUNDARY_LIMITED") == 154 and control.get("M0_NOT_REJECTED") == 86,
        control,
    )

    # ---- Lens 7: search-freedom ------------------------------------------
    check(
        "7_search_free",
        "A1 decomposition ran zero searches and never imported PySR",
        a1["searches_run"] == 0 and not a1["pysr_imported"],
        f"searches_run={a1['searches_run']}",
    )
    check(
        "7_search_free",
        "G2 trace ran zero searches and never imported PySR",
        trace["searches_run"] == 0 and not trace["pysr_imported"],
        f"searches_run={trace['searches_run']}",
    )
    check(
        "7_search_free",
        "PySR is absent from this process",
        "pysr" not in sys.modules,
        "sys.modules scan",
    )

    # ---- Lens 8: claim discipline ----------------------------------------
    bound = trace["observability_bound"]
    check(
        "8_claim_discipline",
        "the within-seed Pareto observability bound is recorded with the trace",
        bound["id"] == "WITHIN_SEED_PARETO_NOT_OBSERVABLE" and bool(bound["statement"]),
        bound["id"],
    )
    # Any case labelled a search-generation failure must actually have zero
    # correct seeds among the persisted retained candidates.
    bad = [
        r
        for r in g2
        if r["root_cause_class"] == "SEARCH_GENERATION_FAILURE"
        and int(r["seeds_with_g2_success"]) > 0
    ]
    check(
        "8_claim_discipline",
        "no SEARCH_GENERATION_FAILURE case had a correct retained candidate",
        not bad,
        f"{len(bad)} contradictory rows",
    )
    # Any case labelled a selection failure must actually have one.
    bad = [
        r
        for r in g2
        if r["root_cause_class"]
        in {"SELECTION_FAILURE", "STABILITY_VOTING_FAILURE", "CANONICALIZATION_EQUIVALENCE_FAILURE"}
        and int(r["seeds_with_g2_success"]) == 0
    ]
    check(
        "8_claim_discipline",
        "every selection-class failure had at least one correct retained candidate",
        not bad,
        f"{len(bad)} contradictory rows",
    )
    # Representability failures must be exactly the families whose truth needs
    # an operator the grammar lacks.
    rep = [r for r in g2 if r["root_cause_class"] == "GRAMMAR_REPRESENTABILITY"]
    check(
        "8_claim_discipline",
        "grammar-representability failures are exactly the exp-family cases",
        len(rep) == 12
        and {r["family_id"] for r in rep} == {"F18"}
        and all(r["operators_missing_from_grammar"] == "exp" for r in rep),
        f"{len(rep)} rows, families {sorted({r['family_id'] for r in rep})}",
    )

    failed = [f for f in FINDINGS if f["status"] == "FAIL"]
    write_json(
        OUT_DIR / "hostile_review.json",
        {
            "lenses": 8,
            "checks": len(FINDINGS),
            "passed": len(FINDINGS) - len(failed),
            "failed": len(failed),
            "overall": "PASS" if not failed else "FAIL",
            "findings": FINDINGS,
        },
    )
    for finding in FINDINGS:
        mark = "ok  " if finding["status"] == "PASS" else "FAIL"
        print(f"  [{mark}] {finding['lens']:18s} {finding['check']}")
    print(f"\n  {len(FINDINGS) - len(failed)}/{len(FINDINGS)} checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
