"""Generate the study's markdown reports from machine-readable artifacts.

Writes `TYPE2_NULL_CALIBRATION.md` and `TYPE2_ENGINE_VALIDATION.md`. Every
number is read from an artifact; nothing is typed by hand.

    python scripts/ov_50_reports.py
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "VECLIB_MAXIMUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ[_v] = "1"

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
ART = ROOT / "artifacts"

HEADER = """Generated by `scripts/ov_50_reports.py` from machine-readable
artifacts of the prospective objective-alignment validation study.
Pre-registration: `TYPE2_VALIDATION_PREREGISTRATION.md` (sha256 `{prereg}`,
committed `{commit}`), frozen **before** any fresh validation world was
generated. This study does not modify Phase 3, whose verdict remains
`STOP BEFORE PHASE 4`.
"""


def _prereg() -> tuple[str, str]:
    p = ART / "ov_prereg_hash.json"
    if p.exists():
        d = json.loads(p.read_text())
        return d.get("sha256", "unrecorded"), d.get("commit", "unrecorded")
    return "unrecorded", "unrecorded"


def null_calibration_md() -> str:
    cal = json.loads((ART / "ov_null_calibration.json").read_text())
    fp = json.loads((ART / "ov_false_positives.json").read_text()) \
        if (ART / "ov_false_positives.json").exists() else None
    prereg, commit = _prereg()

    rows = []
    for c in range(1, cal["max_complexity"] + 1):
        rows.append(f"| {c} | {cal['median'][c]:+.4f} | **{cal['threshold'][c]:+.4f}** "
                    f"| [{cal['threshold_ci_lo'][c]:+.4f}, "
                    f"{cal['threshold_ci_hi'][c]:+.4f}] |")

    pc = "\n".join(
        f"| `{k}` | {v['n']} | {v['p95_c10']:+.4f} | {v['p95_c20']:+.4f} |"
        for k, v in sorted(cal["per_construction_p95"].items()))

    out = f"""# TYPE2_NULL_CALIBRATION.md

{HEADER.format(prereg=prereg, commit=commit)}
Genetic programming always returns something, so a raw symbolic-regression score
means nothing on its own. The threshold a reported Type 2 family must clear is
built empirically, **at its own complexity**, from fresh worlds where no valid
structural conjecture exists.

## The statistic — unchanged from Phase 3, and why

{cal['statistic']}.

{cal['why_unchanged']}.

## Design

| Item | Value |
|---|---|
| Calibration worlds | **{cal['n_calibration_worlds']}** (block `NCAL`), fresh |
| Phase 3's calibration size | 40 — recorded as open issue I8 in `BACKLOG.md` |
| Null constructions | 4, cycled across worlds |
| Seeds per world | 30 |
| Quantile | {cal['quantile']:.0%} |
| Bootstrap resamples on the quantile | {cal['n_bootstrap']} |
| Monotonicity | thresholds made non-decreasing in complexity |
| Disjointness | calibration worlds are disjoint from the 100 `G4` worlds that measure the false-positive rate |

## Threshold table

| Complexity | Null median | **95th percentile threshold** | 95% bootstrap interval on the threshold |
|---|---|---|---|
{chr(10).join(rows)}

### The gap between the median and the threshold is the point

At complexity 20 the null **median** best-of-30-seeds R² is
{cal['median'][20]:+.4f}; the **95th percentile** is {cal['threshold'][20]:+.4f}.
In a world where no descriptor-level relationship exists at all, the best of
thirty symbolic searches reaches that by chance alone. A candidate compared
against a naive single-model null would clear it easily and be reported as a
discovery.

### The threshold's own uncertainty

Mean interval width across complexities:
{sum(cal['interval_width'][1:]) / len(cal['interval_width'][1:]):.4f}.
The point estimate is the frozen gate, as pre-registered; the interval is
reported so the table is not read as more precise than it is, and the decision
rule additionally requires accepted positive-control candidates to clear the
interval's **upper** bound, not merely the point estimate.

## Per-construction check

| Construction | Worlds | p95 at c=10 | p95 at c=20 |
|---|---|---|---|
{pc}

Reported separately so a single pathological construction is visible rather than
buried in the pooled quantile.
"""
    if fp:
        lo, hi = fp["clopper_pearson_95"]
        out += f"""
## G4 false-positive experiment

Each of the {fp['n']} fresh `G4` replicates ran the frozen 30-seed search, the
frozen Type 2 selection rule, and the complete acceptance rule including the
falsification harness.

```
false-positive rate = {fp['accepted']} / {fp['n']} = {fp['rate']:.4f}
```

| Quantity | Value |
|---|---|
| Numerator (null worlds producing an accepted Type 2 family) | **{fp['accepted']}** |
| Denominator (valid null replicates) | **{fp['n']}** |
| Rate | **{fp['rate']:.4f}** |
| Clopper–Pearson exact 95% interval | **[{lo:.4f}, {hi:.4f}]** |
| Criterion | ≤ 5% |

A point estimate of 0/N does not license the claim that the population rate is
zero; the interval is the claim. `p = 0` language is not used for a finite
simulation count.
"""
    return out


def engine_validation_md() -> str:
    ev = json.loads((ART / "ov_engine_validation.json").read_text())
    v, s, t, c = (ev["versions"], ev["smoke_test"], ev["type2_checks"],
                  ev["checkpointability"])
    prereg, commit = _prereg()
    proxies = "\n".join(f"| `sqrt({k})` | {x:.4f} |"
                        for k, x in t["mass_block_exponent_by_proxy"].items())
    worked = "\n".join(f"| `{k}` | {x} |"
                       for k, x in t["complexity_worked_examples"].items())
    return f"""# TYPE2_ENGINE_VALIDATION.md

{HEADER.format(prereg=prereg, commit=commit)}
Master plan §10: verify installation, the Julia runtime, deterministic seeding as
far as the library permits, checkpointability, operator definitions, complexity
scoring, and a smoke test on a known equation. This file additionally checks the
two properties the Type 2 machinery adds.

**Successful installation is not scientific validation.** This file records only
that the engine does what the protocol assumes it does.

## Environment

| Component | Version |
|---|---|
| PySR | **{v['pysr']}** |
| SymbolicRegression.jl | {v.get('SymbolicRegression_jl', 'unavailable')} |
| Julia | {v.get('julia', 'unavailable')} |
| gplearn (comparison arm) | {v['gplearn']} |
| SymPy | {v['sympy']} |
| NumPy / pandas | {v['numpy']} / {v['pandas']} |
| scikit-learn / SciPy | {v['scikit_learn']} / {v['scipy']} |
| Python | {v['python']} |
| Platform | {v['platform']}, {v['cpu_count']} cores |

## Smoke test

Planted: `{s['planted']}` on clean data.

| Quantity | Value |
|---|---|
| Pareto front size | {s['front_size']} |
| Wall time | {s['wall_s']:.2f} s |
| **Recovered** | **{s['recovered']}** |
| Recovered expression | `{s['recovered_expression']}` |
| Recovered complexity | {s['recovered_complexity']} |
| Symbolically equivalent | {s['symbolically_equivalent']} |
| Best validation R² on the front | {s['best_valid_r2']:.6f} |

## Determinism

| Check | Result |
|---|---|
| Two runs at the same seed produce an identical Pareto front | **{s['identical_front_at_same_seed']}** |
| A different seed produces a different front | {s['different_front_at_different_seed']} |

PySR runs with `deterministic=True` and `parallelism='serial'`; reproducibility
is asserted at the setting every governed run uses.

## Type 2 additions

| Check | Result |
|---|---|
| The cached-compile evaluator agrees bit-for-bit with `grammar.evaluate` | **{t['compiled_evaluator_matches_frozen_evaluator']}** |
| The mass-block exponent is invariant to which size proxy is written | **{t['mass_block_exponent_is_proxy_invariant']}** |

| Expression | Mass-block exponent |
|---|---|
{proxies}

## Complexity, one metric everywhere

| Expression | Complexity |
|---|---|
{worked}

Protected numerics: `1/(a-a)` and `log(a-b)` on an in-domain matrix are marked
invalid rather than raising or scoring
({json.dumps(t['protected_numerics'])}). Invalidity can never improve a score.

## Checkpointability

| Property | Result |
|---|---|
| Unit | `{c['unit']}` |
| Resume skips completed units | {c['resume_skips_completed']} |
| A truncated file counts as incomplete, not as a result | {c['truncated_file_counts_as_incomplete']} |
| Write | {c['write']} |
"""


def main() -> int:
    if (ART / "ov_null_calibration.json").exists():
        (ROOT / "TYPE2_NULL_CALIBRATION.md").write_text(null_calibration_md())
        print("[ov50] wrote TYPE2_NULL_CALIBRATION.md", flush=True)
    if (ART / "ov_engine_validation.json").exists():
        (ROOT / "TYPE2_ENGINE_VALIDATION.md").write_text(engine_validation_md())
        print("[ov50] wrote TYPE2_ENGINE_VALIDATION.md", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
