"""Render MURU_WUR_STAGE2A_BASELINE_RESULT.md from artifacts/wur_stage2a.

Formatting only. Every number is read from the committed result files; the
narrative sections are written by hand afterwards in the document itself.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "artifacts" / "wur_stage2a"


def f(x, nd=4):
    if x is None:
        return "n/a"
    try:
        if isinstance(x, float) and (x != x):
            return "nan"
        return f"{x:.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def ci(v, nd=3):
    if not v or v[0] is None:
        return "n/a"
    return f"[{v[0]:.{nd}f}, {v[1]:.{nd}f}]"


def render(results: dict, per_analysis: dict) -> str:
    L = []
    L.append("# MURU WUR Stage 2A: frozen pre-WUR MURU baseline, result tables\n")
    L.append("Generated by `scripts/report_wur_stage2a.py` from `artifacts/wur_stage2a/`. "
             "Narrative interpretation follows the tables and is written by hand.\n")
    c = results["census"]
    L.append("## Populations\n")
    L.append("| Population | Compounds | Scaffold groups | Keys sha256 |\n|---|---|---|---|")
    L.append(f"| LCSB-DEV | {c['lcsb_dev']['n_keys']} | {c['lcsb_dev']['n_scaffold_groups']} | `{c['lcsb_dev']['keys_sha256'][:16]}...` |")
    L.append(f"| WUR-DEV-ANALYSIS | {c['wur_dev_analysis']['n_keys']} | {c['wur_dev_analysis']['n_scaffold_groups']} | `{c['wur_dev_analysis']['keys_sha256'][:16]}...` |")
    p = c["pooled"]
    L.append(f"| A pooled (LCSB copy kept for {p['n_both_lcsb_kept']} population-B keys) | {p['n_pooled_keys']} | see analysis table | |")
    L.append("")
    L.append(f"WUR spectra decoded: {c['wur_dev_analysis']['n_spectra']} in {c['wur_dev_analysis']['n_cells']} cells; "
             f"spectra per cell {c['wur_dev_analysis']['spectra_per_cell']}; descriptor failures: "
             f"{len(c['wur_dev_analysis']['descriptor_failures'])}. LCSB rungs per key: {c['lcsb_dev']['rungs_per_key']}. "
             f"Energy map a={c['energy_map']['a']:.6f}, b={c['energy_map']['b']:.6f}; mapped targets "
             f"{ {k: round(v, 2) for k, v in c['energy_map']['mapped_targets'].items()} }.\n")

    for name, r in per_analysis.items():
        L.append(f"## {name}\n")
        if r.get("failed"):
            L.append("**FAILED**\n```\n" + r["traceback"] + "\n```\n")
            continue
        pop = r["population"]
        L.append(f"World `{r['world_id']}`: {pop['n_compounds']} compounds, {pop['n_scaffold_groups']} scaffold groups, "
                 f"energies {pop['energies']}, split {pop['split_counts']} (groups {pop['split_groups']}), "
                 f"sources {pop['by_source']}.\n")
        col = r["collapse"]; h = col["hmain"]
        L.append("### E1 Collapse and H-MAIN\n")
        L.append("| Quantity | Value |\n|---|---|")
        L.append(f"| Residual SD (mu) | {f(col['resid_sd'])} |")
        L.append(f"| Collapse LOEO RMSE | {f(h['collapse_loeo_rmse'])} |")
        L.append(f"| Free-shape LOEO RMSE | {f(h['free_shape_loeo_rmse'])} |")
        L.append(f"| Ratio (95% CI) | {f(h['ratio'])} {ci(h['ci'])} |")
        L.append(f"| H-MAIN rejected | {h['h_main_rejected']} |")
        g = col["g_hat_summary"]
        L.append(f"| g_hat min / median / max, SD of log g | {f(g['min'],3)} / {f(g['median'],3)} / {f(g['max'],3)}, {f(g['log_sd'],3)} |")
        L.append("")
        lad = r["ladder"]
        L.append("### E2 M0 to M3 adequacy ladder (test split)\n")
        L.append(f"Status **{lad['status']}**; fired {lad['fired'] or 'none'}; Phi trained on {lad['n_train_for_phi']} compounds"
                 + (f"; blocker: {lad['blocker']}" if lad['blocker'] else "") + "\n")
        L.append("| Detector | N_test | Evaluable (min) | Wins (min) | Win frac of test (Wilson 95%) | Binomial tail | Fired | Status counts |")
        L.append("|---|---|---|---|---|---|---|---|")
        for d, s in lad["per_detector"].items():
            sc = {k: v for k, v in s["status_counts"].items() if v}
            L.append(f"| {d} | {s['n_test']} | {s['evaluable']} ({s['min_evaluable']}) | {s['practical_wins']} ({s['min_wins']}) | "
                     f"{f(s['win_fraction_of_test'],3)} {ci(s['win_fraction_wilson95'])} | {f(s['directional_null_tail'],3)} | {s['fired']} | {sc} |")
        L.append("")
        sel = r["selection"]; gt = sel["gate"]
        L.append("### E3, E4 Frozen selector and gate\n")
        L.append("| Quantity | Value |\n|---|---|")
        L.append(f"| Seeds done / planned | {r['search']['n_seeds_done']} / {r['search']['n_seeds_planned']} (failures {len(r['search']['failures'])}) |")
        L.append(f"| Gate decision | **{'REPORT' if sel['report'] else 'NO_REPORT'}** (t1={gt['t1']}, t2={gt['t2']}) |")
        L.append(f"| median seed-best validation R2 | {f(gt['features']['median_seed_best_r2'])} |")
        L.append(f"| selection fraction | {f(gt['features']['selection_fraction'])} |")
        L.append(f"| modal support frequency | {f(gt['features']['modal_support_freq'])} |")
        L.append(f"| band members / usable / clusters | {sel['n_members']} / {sel['n_usable']} / {sel['n_clusters']} |")
        L.append(f"| representative | `{sel['expr']}` |")
        L.append(f"| complexity | {sel['complexity']} |")
        L.append(f"| effective support (blocks) | {sel['eff_support']} ({sel['eff_blocks']}) |")
        L.append(f"| train / validation R2 | {f(sel.get('train_r2'))} / {f(sel['valid_r2'])} |")
        ht = sel.get("heldout_test")
        if ht:
            L.append(f"| **test R2 weighted / unweighted** | **{f(ht['r2_weighted'])}** / {f(ht['r2_unweighted'])} (n={ht['n']}, invalid {f(ht['invalid_fraction'],3)}) |")
            L.append(f"| test Spearman | {f(ht['spearman'])} |")
            L.append(f"| test R2 bootstrap 95% | {ci(r['bootstrap'].get('rep_test_r2_weighted_ci95'))} |")
        L.append("")
        sb = sorted(x for x in sel["seed_best_valid_r2"] if x == x)
        if sb:
            L.append(f"E5 seed-best validation R2: min {f(sb[0],3)}, q25 {f(sb[len(sb)//4],3)}, median {f(sb[len(sb)//2],3)}, "
                     f"q75 {f(sb[3*len(sb)//4],3)}, max {f(sb[-1],3)} over {len(sb)} seeds.\n")
        bt = r["bootstrap"]
        L.append("Bootstrap (compound-level, n=1000): " + "; ".join(
            f"{d}: evaluable {ci(bt[d]['evaluable_fraction_ci95'])}, wins {ci(bt[d]['win_fraction_ci95'])}"
            for d in ("M1", "M2", "M3") if d in bt) + ".\n")
        de = r["descriptives"]["per_energy_mu"]
        L.append("### E8 Per-energy mu (median [q25, q75]) by source\n")
        L.append("| E | n | all | " + " | ".join(sorted({s for v in de.values() for s in v['by_source']})) + " |")
        srcs = sorted({s for v in de.values() for s in v['by_source']})
        L.append("|---|---|---|" + "---|" * len(srcs))
        for e, v in de.items():
            L.append(f"| {float(e):g} | {v['n']} | {f(v['median'],3)} [{f(v['q25'],3)}, {f(v['q75'],3)}] | "
                     + " | ".join(f(v['by_source'].get(s), 3) for s in srcs) + " |")
        if "e15_separate" in r["descriptives"]:
            e15 = r["descriptives"]["e15_separate"]
            L.append(f"\nE7 E = 15, separate: WUR native n={e15['wur_native_e15']['n']} median {f(e15['wur_native_e15']['median'],3)} "
                     f"[{f(e15['wur_native_e15']['q25'],3)}, {f(e15['wur_native_e15']['q75'],3)}]; LCSB native n={e15['lcsb_native_e15']['n']} "
                     f"median {f(e15['lcsb_native_e15']['median'],3)} [{f(e15['lcsb_native_e15']['q25'],3)}, {f(e15['lcsb_native_e15']['q75'],3)}].")
        L.append(f"\nWall time {r['seconds']:.0f} s.\n")
    L.append("## Reproducibility\n")
    env = json.loads((OUT / "manifest.json").read_text())["environment"]
    L.append(f"Manifest sha256 `{results['manifest_sha256']}`; environment {env}.\n")
    return "\n".join(L)


def main(out_dir: Path = OUT, dest: Path | None = None) -> str:
    results = json.loads((out_dir / "stage2a_results.json").read_text())
    per = {}
    for name in results["analyses"]:
        per[name] = json.loads((out_dir / name / "result.json").read_text())
    text = render(results, per)
    if dest:
        dest.write_text(text)
    return text


if __name__ == "__main__":
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    text = main(dest=dest)
    print(text[:3000] if dest is None else f"wrote {dest}")
