"""Generate the Phase 2 markdown artifacts from the machine-readable results.

Every number in every report is read from a JSON artifact produced by an earlier
script. Nothing is transcribed by hand, so the reports cannot drift from the
evidence.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"


def load(name):
    return json.loads((ART / name).read_text())


split = load("p2_split_audit.json")
desc = load("p2_descriptor_audit.json")
diag = load("p2_prereg_diagnostics.json")
coup = load("p2_mass_coupling.json")
base = load("p2_baselines.json")
var = load("p2_variance.json")
ctrl = load("p2_controls.json")
rob = load("p2_robustness.json")

HDR = ("Generated by `scripts/t2_09_reports.py` from machine-readable Phase 2\n"
       "artifacts. Pre-registration: `PREREGISTRATION.md`\n"
       "(sha256 `4cfc623361a62e64f4c5a8720c3ccf3ffea6ed2b1ed86f53b7154e5acb6e6d17`,\n"
       "committed `ddcdb8de1b69480178495bc0ec89e7fdce7a6dda`).\n")

MODELS = ["B0_global_mean", "B1_per_energy_mean", "B2_MASS_SIMPLE", "MASS_FLEX",
          "TIER_A", "TIER_A_no_mass", "TIER_A_mass_only", "FLEX_BENCHMARK",
          "FLEX_BENCHMARK_no_mass"]


def w(name: str, lines: list[str]):
    (ROOT / name).write_text("\n".join(lines) + "\n")
    print(f"wrote {name}")


# ===========================================================================
# SPLIT_AUDIT.md
# ===========================================================================
s, c, cf, sp = split["scaffold"], split["cluster"], split["confirmation"], split["splits"]
L = [f"# SPLIT_AUDIT.md", "", HDR,
     "Split construction is part of the science, so every split is audited",
     "before it is used and the audit is reported whether or not it is",
     "flattering (Phase 2 instruction 4).", "",
     "## Connectivity key", "",
     "InChIKey **first block** (connectivity layer). Every collision energy and",
     "every internal MassBank ID sharing a connectivity moves together.",
     "Disjointness is enforced by assertion in `src/muru/splits.py`, not by",
     "inspection; `tests/test_splits.py` plants a violation and requires the",
     "assertion to catch it.", "",
     "## Bemis-Murcko scaffold audit (S2)", "",
     "| Quantity | Value |", "|---|---|",
     f"| Compounds | {split['n_compounds']} |",
     f"| Unique non-empty Murcko scaffolds | {s['n_unique_murcko_nonempty']} |",
     f"| Compounds with an **empty** scaffold (ringless) | {s['n_acyclic_empty_murcko']} ({100*s['frac_acyclic']:.1f}%) |",
     f"| Scaffold groups after the ringless policy | {s['n_scaffold_groups_after_policy']} |",
     f"| Singleton groups | {s['n_singleton_groups']} ({100*s['frac_compounds_in_singletons']:.1f}% of compounds) |",
     f"| Largest group as a share of the corpus | **{100*s['max_group_frac_of_corpus']:.1f}%** |", "",
     "### Scaffold group-size distribution", "",
     "| Group size | Number of groups |", "|---|---|"]
L += [f"| {k} | {v} |" for k, v in s["group_size_distribution"].items()]
L += ["", "### Largest scaffold groups", "", "| Scaffold | Compounds |", "|---|---|"]
L += [f"| `{g['scaffold']}` | {g['n']} |" for g in s["largest_groups"]]
L += ["", "### Ringless / empty-scaffold policy", "",
      "Bemis-Murcko is **undefined** for a molecule with no ring system:",
      "`GetScaffoldForMol` returns an empty molecule. Keying on the returned",
      "SMILES would place every acyclic compound into one group named by the",
      "empty string, asserting a shared core that does not exist.", "",
      f"**Policy.** Each of the {s['n_acyclic_empty_murcko']} ringless compounds becomes its own",
      "scaffold group, keyed by its connectivity block. They are **not** pooled.", "",
      "**Declared consequence.** S2 is marginally *easier* for those",
      f"{100*s['frac_acyclic']:.1f}% of compounds, because scaffold-disjointness is",
      "undefined for them. S3 clusters them properly by similarity and is the",
      "stress test that covers them. This was recorded before any performance",
      "was observed (`MASTER_PLAN_CLARIFICATIONS.md` C5).", "",
      "### S2 verdict", "",
      f"**Pathological: {split['s2_verdict']['pathological']}.** {split['s2_verdict']['reason']}", "",
      "## Similarity clustering (S3)", "",
      "RDKit's `Butina.ClusterData` takes a **distance** cutoff, not a",
      "similarity. The pre-registered Tanimoto **similarity** threshold is",
      f"**{c['similarity_threshold']}**, applied as distance cutoff",
      f"**{c['distance_cutoff_used']}** (`distance = 1 - similarity`).", "",
      "Passing 0.6 directly as a distance would have clustered everything above",
      "Tanimoto similarity 0.4 — a far looser grouping that would have made the",
      "cluster-disjoint split silently easier. `tests/test_splits.py` pins the",
      "conversion with synthetic bit vectors of hand-computed similarity,",
      "including a regression test that a pair at similarity 0.4 is **not**",
      "merged under a 0.6 similarity threshold.", "",
      "| Quantity | Value |", "|---|---|",
      f"| Clusters | {c['n_clusters']} |",
      f"| Singleton clusters | {c['n_singleton_clusters']} ({100*c['frac_compounds_in_singletons']:.1f}% of compounds) |",
      f"| Largest cluster sizes | {c['largest_clusters']} |",
      f"| Largest cluster as a share of the corpus | {100*c['max_cluster_frac_of_corpus']:.1f}% |", "",
      "S3 is much finer than S2: 83% of compounds are in singleton clusters, so",
      "it is a genuinely harder generalization test.", "",
      "## Confirmation set — SEALED", "",
      "| Quantity | Value |", "|---|---|",
      f"| Compounds | **{cf['n_compounds']}** ({100*cf['frac']:.2f}%) |",
      f"| Scaffold groups | {cf['n_scaffold_groups']} |",
      f"| Development compounds | {cf['development_n_compounds']} |",
      f"| Artifact | `artifacts/confirmation_set_sealed.json` |",
      f"| SHA-256 | `{cf['sha256']}` |", "",
      "**Not opened in Phase 2.** No endpoint value from these compounds was",
      "loaded, no performance computed, no descriptor chosen, no threshold",
      "tuned, no model compared.", "",
      "### Disclosure", "",
      "These compounds are **not** unseen with respect to all study design.",
      "Phase 1 used the full positive-mode corpus — including them — to select",
      "mu, compare endpoints, characterize monotonicity and evaluate",
      "confounding. The only defensible statement, and the one this project",
      "makes, is in `PREREGISTRATION.md` §4.1.", "",
      "## Fold structure (development corpus)", "",
      f"{sp['development_compounds']} compounds, {sp['development_rows']} rows, {sp['n_folds']} folds.", "",
      "| Split | Compounds per fold |", "|---|---|"]
for k in ("S1", "S2", "S3"):
    L.append(f"| {k} | {list(sp['fold_compound_counts'][k].values())} |")
L += ["", "Fold assignment fills groups largest-first into the currently",
      "smallest fold, so the 80-compound benzene group cannot dominate one fold.",
      "", "## Leakage canary (S0)", "",
      "S0 assigns folds per **row**, so a molecule's six energies land on both",
      "sides of the wall — the trivial failure mode the project files warn about.",
      "",
      f"Fraction of compounds split across folds under S0: **{100*sp['S0_frac_compounds_split_across_folds']:.1f}%**.",
      "The canary therefore does exercise the intended failure mechanism.", ""]
lc = base["leakage_canary"]
L += ["| Model | S0 leaked MAE | S2 honest MAE | Optimism |", "|---|---|---|---|"]
for m, v in lc["comparison"].items():
    L.append(f"| {m} | {v['S0_leaked_mae']:.5f} | {v['S2_honest_mae']:.5f} | "
             f"{v['inflation_pct']:+.1f}% |")
L += ["", f"**Canary fires: {lc['fires']}.**", "",
      "S0 numbers are a **diagnostic** measuring the size of the leakage gap.",
      "They are never reported as scientific performance.", ""]
w("SPLIT_AUDIT.md", L)

# ===========================================================================
# DESCRIPTORS.md
# ===========================================================================
ta, tb = desc["tier_a"], desc["tier_b"]
RATIONALE = {
    "precursor_mz": ("m/z", "sets E_lab and is the denominator of mu; the mass carrier"),
    "total_atom_count": ("count", "vibrational degrees of freedom proxy (3N-6), H included"),
    "rotatable_bonds": ("count", "low-frequency mode density, energy sink capacity"),
    "ring_count": ("count", "rigidity; rings raise dissociation thresholds"),
    "aromatic_ring_count": ("count", "stabilizing substructures"),
    "rdbe": ("count", "degree of unsaturation, bond-strength proxy"),
    "tpsa": ("A^2", "proton affinity / charge localization proxy"),
    "heteroatom_fraction": ("fraction", "charge localization; scale-free, so least mass-coupled"),
    "n_N": ("count", "preferred cleavage site"),
    "n_O": ("count", "preferred cleavage site"),
    "n_S": ("count", "preferred cleavage site"),
    "n_halogen": ("count", "preferred cleavage site"),
}
L = ["# DESCRIPTORS.md", "", HDR,
     "Tier A and Tier B were frozen **before any Phase 2 outcome model was",
     "fitted**, and computed from sanitized SMILES only, so the freeze is blind",
     "to mu. Confirmation-set compounds were excluded entirely: they informed no",
     "descriptor choice.", "",
     f"Development compounds: **{desc['n_development_compounds']}**. "
     f"Confirmation compounds excluded: {desc['n_confirmation_excluded']}.", "",
     "## Tier A — frozen, 12 descriptors", "",
     "| Descriptor | Units | Missing | Distinct | Range | Median | Rationale |",
     "|---|---|---|---|---|---|---|"]
for d in ta["frozen_list"]:
    su = desc["tier_a_summary"][d]
    u, r = RATIONALE[d]
    L.append(f"| `{d}` | {u} | {su['n_missing']} | {su['n_distinct']} | "
             f"{su['min']:.4g} – {su['max']:.4g} | {su['median']:.4g} | {r} |")
L += ["", f"Computation failures: **{ta['n_failures']}**. "
      "Implementation: RDKit 2026.03.5 via `src/muru/molecules.py`; "
      "`precursor_mz` is taken from the MassBank record, not recomputed.", "",
      "## Dropped candidates and why", "",
      "The retention rule, applied before any outcome was observed: computable",
      "for every compound, non-degenerate, mechanistically motivated, and not",
      "rank-redundant with a descriptor already retained.", "",
      "| Dropped | Reason |", "|---|---|",
      "| `exact_mass`, `mol_wt` | Spearman **1.000** with `precursor_mz` — rank-identical and mathematically dependent (`precursor_mz = exact_mass + 1.00728`) |",
      "| `labute_asa` | 0.985 with mass, 0.993 with heavy-atom count. The master plan's 'molecular volume / CCS proxy' slot carries nothing beyond mass at this resolution and would contaminate the K5 mass ablation |",
      "| `heavy_atom_count` | 0.974 with mass, 0.903 with `total_atom_count`, which is the principled 3N−6 proxy |", "",
      "**Descriptors were not added later because cross-validation performance",
      "was disappointing.** The list is the one frozen in the pre-registration.", "",
      "## Collinearity structure", "",
      f"Severe (|rho| >= 0.90) pairs remaining: **{len(desc['tier_a_collinearity']['severe_ge_0.90'])}**. "
      f"Maximum off-diagonal |rho|: **{desc['tier_a_collinearity']['max_abs_offdiagonal']}**.", "",
      "Strong (0.70 <= |rho| < 0.90):", "",
      "| a | b | Spearman rho |", "|---|---|---|"]
for p in desc["tier_a_collinearity"]["strong_0.70_to_0.90"]:
    L.append(f"| `{p['a']}` | `{p['b']}` | {p['rho']} |")
L += ["", "### Variance inflation", "",
      "| Descriptor | VIF |", "|---|---|"]
for k, v in desc["tier_a_vif"].items():
    L.append(f"| `{k}` | {v} |")
L += ["", "**Consequence, declared in advance.** VIF is high for `precursor_mz`",
      f"({desc['tier_a_vif']['precursor_mz']}) and `total_atom_count`",
      f"({desc['tier_a_vif']['total_atom_count']}). Individual Tier A coefficients and",
      "per-descriptor importances are therefore **not interpreted causally**, and",
      "importance is reported over correlated blocks. Prediction is unaffected by",
      "collinearity; interpretation is.", "",
      "### Mass block for the K5 ablation", "",
      f"`{'`, `'.join(ta['mass_block_for_ablation'])}` are removed **together**.",
      "Dropping the named mass variable alone would leave its proxies in place",
      "and understate how much of the effect mass carries.", "",
      "## Tier B — frozen", "",
      "| Component | Value |", "|---|---|",
      f"| Morgan fingerprints | radius {tb['morgan_radius']}, {tb['morgan_nbits']} bits |",
      f"| Bits ever set | {tb['n_fingerprint_bits_ever_set']} |",
      f"| Bits retained (set in >= 5 molecules, see DEVIATIONS D12) | {base['setup']['tier_b_fp_bits_kept']} |",
      f"| RDKit descriptor block | {tb['n_rdkit_descriptors']} descriptors |",
      f"| NaN cells in the RDKit block | {tb['n_rdkit_nan_cells']} |",
      f"| **Total features used** | **{base['setup']['tier_b_n']}** |", "",
      "No learned embeddings, no graph neural networks, no AutoML. Tier B is a",
      "finite pre-registered benchmark, not a feature search, and it was not",
      "expanded after performance was observed.", ""]
w("DESCRIPTORS.md", L)

# ===========================================================================
# MASS_COUPLING_AUDIT.md
# ===========================================================================
L = ["# MASS_COUPLING_AUDIT.md", "", HDR,
     "Precursor mass appears in the definition of the response:", "",
     "```",
     "mu = (sum_k I_k * mz_k) / (sum_k I_k) / mz_precursor",
     "```", "",
     "so an apparent association between mu and precursor mass may be produced",
     "**mechanically by the normalization** rather than by chemistry. This audit",
     "asks one question:", "",
     "> Can the definition of mu itself produce an apparent association with",
     "> precursor mass even when the underlying **fractional** fragmentation",
     "> behaviour is held constant?", "",
     "It is a Phase 2 response-variable audit. It is **not** the Phase 3",
     "synthetic discovery system: there is no search, no hidden ground-truth",
     "equation, and no discovery engine.", "",
     "## Analytic statement", "",
     "Writing SY for survival yield and phi for the intensity-weighted mean",
     "fragment mass as a fraction of the precursor mass,", "",
     "```", "mu = SY + (1 - SY) * phi,   phi = <mz_fragment> / mz_precursor", "```", "",
     "(exactly, up to the ~9 ppm observed/declared precursor ratio Phase 1",
     "quantified as deviation D1). Both terms are dimensionless. Therefore:", "",
     "- **Fractional regime.** If every fragment's m/z is a fixed proportion of",
     "  its precursor and relative intensities are fixed, phi is mass-invariant",
     "  and mu carries **no** mass dependence.",
     "- **Absolute regime.** If fragment m/z is set on an absolute scale,",
     "  `phi ~ 1/mz_precursor`, so mu acquires a negative mass association",
     "  **mechanically, with no chemistry at all**.", "",
     "## Deterministic diagnostic", "",
     f"Real precursor masses from the development corpus ({coup['n_synthetic_compounds']} compounds,",
     f"{coup['mass_range'][0]:.1f}–{coup['mass_range'][1]:.1f} m/z) are combined with a fragmentation",
     "programme that is **identical for every compound** — the same survival",
     "yield per energy, the same relative fragment intensities. Only the *scale*",
     "on which fragment masses are placed changes between regimes.", "",
     "| Regime | rho(mu, precursor m/z) at NCE 90 | max abs rho | Construction |",
     "|---|---|---|---|"]
for k, v in coup["regimes"].items():
    L.append(f"| **{k}** | {v['rho_mu_vs_precursor_mz_by_energy']['90']} | "
             f"{v['max_abs_rho']} | {v['description']} |")
L += ["", "### Per-energy detail", "",
      "| Regime | " + " | ".join(str(e) for e in [15, 30, 45, 60, 75, 90]) + " |",
      "|---|" + "---|" * 6]
for k, v in coup["regimes"].items():
    r = v["rho_mu_vs_precursor_mz_by_energy"]
    L.append(f"| {k} | " + " | ".join(f"{r[str(e)]}" for e in [15, 30, 45, 60, 75, 90]) + " |")
L += ["| **OBSERVED (real data)** | " +
      " | ".join(f"**{coup['observed_rho_by_energy'][str(e)]}**"
                for e in [15, 30, 45, 60, 75, 90]) + " |", "",
      "## Findings", "",
      "**1. Purely fractional fragmentation manufactures nothing.** Regime A",
      f"gives rho = {coup['comparison']['fractional_at_NCE90']} at NCE 90 — numerically zero.",
      "When fractional behaviour is genuinely held constant, mu is mass-invariant,",
      "confirming the analytic statement. The normalization is not intrinsically",
      "pathological.", "",
      "**2. Absolute-scale fragmentation manufactures everything.** Regime B",
      f"gives rho = {coup['comparison']['absolute_at_NCE90']} — a perfect rank association produced",
      "entirely by the denominator, with no chemistry whatsoever.", "",
      "**3. The realistic case is the concerning one.** Regime D applies purely",
      "proportional chemistry plus a **single absolute instrument limit** — a",
      "fixed 50 Da low-mass cutoff, which real instruments have. That alone",
      f"produces rho = {coup['comparison']['absolute_floor_at_NCE90']} at NCE 90, a correlation of the same",
      f"sign and a magnitude comparable to the observed {coup['comparison']['observed_at_NCE90']}.", "",
      "> **What this does and does not establish.** This is a *sensitivity and",
      "> mechanistic-coupling* diagnostic. It shows that a mass association of",
      "> roughly this magnitude **can** be generated with no chemistry at all.",
      "> It does **not** identify what fraction of the observed association is",
      "> artifactual. The diagnostic is not fitted to the data, its fragment",
      "> programme is stipulated rather than estimated, and no counterfactual",
      "> version of this corpus without the coupling exists. Attributing a",
      "> percentage to the artifact would require identification this design",
      "> does not have. The correct reading is: **mass dependence of mu is not,",
      "> by itself, evidence of chemistry.**", "",
      "**4. On the real data the association migrates into the fragment term.**",
      "rho against precursor mass, by component:", "",
      "| NCE | rho(mu, mass) | rho(phi, mass) | rho(SY, mass) |", "|---|---|---|---|"]
for e in [15, 30, 45, 60, 75, 90]:
    d = coup["decomposition_of_the_association"][str(e)]
    L.append(f"| {e} | {d['rho_mu_mass']} | {d['rho_phi_mass']} | {d['rho_sy_mass']} |")
L += ["", "At NCE 90, rho(phi, mass) = "
      f"{coup['decomposition_of_the_association']['90']['rho_phi_mass']} is essentially identical to",
      f"rho(mu, mass) = {coup['decomposition_of_the_association']['90']['rho_mu_mass']}. The high-energy mass association is",
      "carried by **phi — the fragment term, where the denominator lives** — not",
      "by survival yield. That is the signature the mechanical-coupling",
      "hypothesis predicts.", "",
      "## Consequence for K5", "",
      "A mass association of the observed sign and comparable magnitude **can**",
      "arise from mu's normalization combined with an absolute low-mass limit,",
      "with no molecular chemistry involved. Two limits on that statement matter:", "",
      "- The diagnostic does **not** decompose the observed association into",
      "  artifactual and chemical parts. It is a sensitivity result, not an",
      "  identification result.",
      "- The observed association *grows* with collision energy (−0.09 to −0.68)",
      "  while regime D's is roughly flat across the grid (−0.46 to −0.53). The",
      "  coupling mechanism alone therefore does not reproduce the observed",
      "  energy dependence, which is evidence that the observed pattern is not",
      "  purely mechanical.", "",
      "What it does establish, and what K5 uses:", "",
      "1. **Mass-dependence of mu is not, by itself, evidence of chemistry**, and",
      "2. any structure claim resting on mass-correlated descriptors must carry",
      "   that caveat explicitly.", "",
      "Mechanically induced mass dependence is **not** treated as",
      "molecular-structure discovery. This finding is carried into the K5",
      "adjudication in `PHASE2_DECISION.md`.", ""]
w("MASS_COUPLING_AUDIT.md", L)

# ===========================================================================
# VARIANCE_DECOMPOSITION.md
# ===========================================================================
adq, hier, vd, k5v = (var["model_adequacy"], var["hierarchical"],
                      var["variance_decomposition"], var["K5_variance_share"])
L = ["# VARIANCE_DECOMPOSITION.md", "", HDR,
     "Answers a different question from the baseline ladder: not *how well can",
     "mu be predicted* but *where does the variance in mu live, and how much of",
     "the between-compound part can structure account for*.", "",
     "## Model adequacy came before model prestige", "",
     "The master plan's §9.2 formulation was treated as a candidate, not as",
     "truth, and was checked before the likelihood was frozen.", "",
     "| Diagnostic | Value | Consequence |", "|---|---|---|",
     f"| mu range | [{adq['mu_min']:.4f}, **{adq['mu_max']:.7f}**] | logit and Beta are **undefined** at the upper end |",
     f"| rows with mu > 1 | **{adq['n_mu_gt_1']}** | caused by the ~9 ppm recalibration effect Phase 1 recorded as D1 |",
     f"| logit(mu) linear in NCE | median R² {diag['logit_linear_in_NCE_fit']['median_r2']:.3f}, {100*diag['logit_linear_in_NCE_fit']['frac_r2_below_0.9']:.1f}% below 0.9 | the two-parameter form does not describe these trajectories |",
     f"| logit(mu) linear in log NCE | median R² {diag['logit_linear_in_logNCE_fit']['median_r2']:.3f}, {100*diag['logit_linear_in_logNCE_fit']['frac_r2_below_0.9']:.1f}% below 0.9 | better, still inadequate |",
     f"| residual SD ratio across energies | {adq['resid_sd_ratio_max_over_min']} | heteroskedasticity mild |",
     f"| Spearman(abs residual, fitted) | {adq['spearman_absresid_vs_fitted']} | no strong mean-variance coupling |", "",
     "**Decisions taken on that evidence**, recorded as `DEVIATIONS.md` D7 and D8:",
     "mu is modelled on the **natural scale**, and energy is treated",
     "**nonparametrically** (6-level factor or spline), never as a two-parameter",
     "linear term. Clipping mu into (0,1) to rescue the logit was rejected: it",
     "would silently edit measured values to suit a modelling convenience.", "",
     "## Why not PyMC", "",
     f"Implementation: **{hier['implementation']}**.", "",
     "A probabilistic programming framework was considered and deliberately not",
     "used (Phase 2 instruction 14). mu has no censoring — that was survival",
     "yield, which Phase 2 does not model as a continuous response; n is ample",
     f"({hier['n_obs']} observations, {hier['n_groups']} compounds); and every interval reported",
     "in Phase 2 comes from a compound-level bootstrap rather than a posterior.",
     "Adding PyMC would have introduced sampler-convergence risk and a second",
     "model definition without changing a single Phase 2 answer. The cost is",
     "that intervals here are frequentist bootstrap intervals, not posterior",
     "credible intervals.", "",
     "## Hierarchical fit", "",
     "`mu ~ C(NCE)` with a compound random intercept and a random slope in",
     "centred energy.", "",
     "| Component | Value |", "|---|---|",
     f"| Converged | {hier['converged']} |",
     f"| Random intercept variance | {hier['var_random_intercept']} |",
     f"| Random slope variance | {hier['var_random_slope']} |",
     f"| Intercept-slope correlation | {hier['corr_intercept_slope']} |",
     f"| Residual variance | {hier['residual_var']} |", "",
     "## Variance decomposition", "",
     "| Component | Variance | Share of total |", "|---|---|---|",
     f"| Energy (fixed) | {vd['energy_fixed']} | **{100*vd['energy_fixed_share']:.1f}%** |",
     f"| Compound identity (random) | {vd['compound_random']} | **{100*vd['compound_random_share']:.1f}%** |",
     f"| Residual | {vd['residual']} | {100*vd['residual_share']:.1f}% |",
     f"| *Total Var(mu)* | {vd['total_var_mu']} | |", "",
     f"Intraclass correlation conditional on energy: **{vd['icc_conditional_on_energy']}**.", "",
     "## Descriptor-explained share of between-compound variance (K5 input)", "",
     "The master plan's K5 threshold is a descriptor-driven between-compound",
     "variance share of **0.20**. Reported both in-sample and cross-validated;",
     "**only the cross-validated figure is used**, because an in-sample R² from",
     "12 descriptors on a few hundred compounds is optimistic by construction.", "",
     "| Target | Feature set | CV R² (scaffold-grouped) | In-sample R² |",
     "|---|---|---|---|"]
for tgt, entry in var["descriptor_explained_between_compound"].items():
    for fname, v in entry.items():
        L.append(f"| `{tgt}` | {fname} | **{v['cv_r2_scaffold_grouped']}** | "
                 f"{v['in_sample_r2']} |")
L += ["", f"**K5 variance-share verdict.** Tier A explains **{k5v['tier_a_full']}** of the",
      f"compound random intercept out of sample (threshold {k5v['threshold']}): meets threshold =",
      f"**{k5v['meets_threshold_full']}**. With the mass block removed the share is",
      f"**{k5v['tier_a_no_mass']}**: meets threshold = **{k5v['meets_threshold_without_mass']}**.", "",
      "The gap between those two numbers is the quantity K5 actually turns on.", ""]
w("VARIANCE_DECOMPOSITION.md", L)

# ===========================================================================
# BASELINES.md
# ===========================================================================
st = base["setup"]
L = ["# BASELINES.md", "", HDR,
     f"Development corpus: **{st['development_compounds']} compounds / {st['development_rows']} rows**, positive mode.",
     f"Primary split: **{st['primary_split']}** (Bemis-Murcko scaffold-disjoint).",
     f"Nested grouped CV: outer 5-fold by the split's group key, inner 4-fold for",
     f"hyperparameters only. Bootstrap: {st['n_boot']} resamples.", "",
     "Every model answers a distinct scientific question. There is no",
     "leaderboard.", "",
     "## The ladder", "",
     "| Model | Question it answers |", "|---|---|",
     "| `B0_global_mean` | floor |",
     "| `B1_per_energy_mean` | is there any energy signal at all |",
     "| `B2_MASS_SIMPLE` | is the effect just mass, simply |",
     "| `MASS_FLEX` | is the effect just mass, **strongly** |",
     "| `TIER_A` | interpretable structure model |",
     "| `TIER_A_no_mass` | structure with the mass block removed (K5) |",
     "| `TIER_A_mass_only` | the mass block alone |",
     "| `FLEX_BENCHMARK` | recoverable nonlinear structural information |",
     "| `FLEX_BENCHMARK_no_mass` | the same, mass-like features removed (K5) |", ""]
for spl in ("S1", "S2", "S3"):
    pf = base["performance"][spl]
    nm = {"S1": "compound-disjoint", "S2": "scaffold-disjoint (PRIMARY)",
          "S3": "cluster-disjoint"}[spl]
    L += [f"## {spl} — {nm}", "",
          f"Resampling unit for the quoted interval: **{pf['resampling_unit']}**.", "",
          "| Model | MAE (compound) | 95% CI (compound) | MAE (unit) | 95% CI (unit) | RMSE | grouped R² |",
          "|---|---|---|---|---|---|---|"]
    for m in MODELS:
        if m not in pf:
            continue
        v = pf[m]
        L.append(f"| `{m}` | **{v['mae']:.5f}** | [{v['mae_ci_compound'][0]:.5f}, "
                 f"{v['mae_ci_compound'][1]:.5f}] | {v['mae_unit']:.5f} | "
                 f"[{v['mae_ci_unit'][0]:.5f}, {v['mae_ci_unit'][1]:.5f}] | "
                 f"{v['rmse']:.5f} | {v['grouped_r2']:.4f} |")
    L += ["", "### Paired comparisons (negative favours the first model)", "",
          "| Comparison | ΔMAE | 95% CI (unit) | Relative reduction | Interval excludes 0 |",
          "|---|---|---|---|---|"]
    for k, v in base["paired"][spl].items():
        L.append(f"| {k.replace('_vs_', ' vs ')} | {v['mae_diff']:+.5f} | "
                 f"[{v['ci_unit'][0]:+.5f}, {v['ci_unit'][1]:+.5f}] | "
                 f"{v['rel_reduction_pct']:+.2f}% | {v['ci_excludes_zero_unit']} |")
    L += [""]
L += ["## R² is reported but is never the decision variable", "",
      "With grouped data and unbalanced coverage, grouped R² depends on the",
      "between-compound variance in the particular split, which changes with the",
      "split. Every decision below rests on **paired compound-level held-out",
      "error**, not on R².", ""]
w("BASELINES.md", L)

# ===========================================================================
# FLEXIBLE_PREDICTIVE_BENCHMARK.md
# ===========================================================================
k4f, k4a_ = base["K4_flexible"], base["K4_tier_a"]
L = ["# FLEXIBLE_PREDICTIVE_BENCHMARK.md", "", HDR,
     "## This is not a ceiling", "",
     "The master plan calls B7 the 'predictability ceiling' and states that",
     "'any baseline beating B7 signals a bug'. Both are too strong, and",
     "`MASTER_PLAN_CLARIFICATIONS.md` C2 revokes them.", "",
     "A gradient-boosted tree ensemble under nested grouped CV is **one model",
     "family with one frozen search space**. It is not an information-theoretic",
     "upper bound on recoverable information, and it is not guaranteed to beat",
     "simpler models — trees are weak at smooth extrapolation along a continuous",
     "axis, which is exactly what `mu ~ f(energy, mass)` is. Treating a loss as",
     "a defect would create pressure to tune until it wins, which is the",
     "researcher degree of freedom the pre-registration exists to remove.", "",
     "**The benchmark was not re-tuned after seeing its results, and its search",
     "space was not enlarged.**", "",
     "## Configuration", "",
     "| Item | Value |", "|---|---|",
     "| Family | `sklearn.ensemble.HistGradientBoostingRegressor` |",
     f"| Features | energy + {st['tier_b_n']} Tier B features ({st['tier_b_fp_bits_kept']} Morgan bits set in ≥ {st['tier_b_min_bit_count']} molecules + 26 RDKit descriptors) |",
     "| Grid | `max_depth ∈ {3,6,None}` × `learning_rate ∈ {0.05,0.1}` × `max_iter ∈ {200,500}` |",
     "| Selection | inner 4-fold grouped CV only; the outer fold never informs selection |", "",
     "The grid and the fingerprint floor were reduced from the originally frozen",
     "values for compute reasons, before any performance was observed",
     "(`DEVIATIONS.md` D12). Both reductions can only **weaken** the benchmark,",
     "so they make K4A and K4B **harder** to pass — the conservative direction.", "",
     "## Selected hyperparameters", "",
     "| Split | Modal configuration |", "|---|---|"]
for spl in ("S1", "S2", "S3"):
    L.append(f"| {spl} | `{base['performance'][spl]['FLEX_BENCHMARK']['hp_modal']}` |")
L += ["", "## Performance against the ladder", "",
      "| Split | B1 | MASS FLEX | TIER_A | FLEX BENCHMARK |", "|---|---|---|---|---|"]
for spl in ("S1", "S2", "S3"):
    p = base["performance"][spl]
    L.append(f"| {spl} | {p['B1_per_energy_mean']['mae']:.5f} | "
             f"{p['MASS_FLEX']['mae']:.5f} | {p['TIER_A']['mae']:.5f} | "
             f"{p['FLEX_BENCHMARK']['mae']:.5f} |")
L += ["", "## Tier B minus Tier A gap", "",
      "The master plan asks for this explicitly: a large gap means the",
      "interpretable model is missing real signal.", "",
      "| Split | ΔMAE (FLEX − TIER_A) | 95% CI (unit) |", "|---|---|---|"]
for spl in ("S1", "S2", "S3"):
    v = base["paired"][spl]["FLEX_BENCHMARK_vs_TIER_A"]
    L.append(f"| {spl} | {v['mae_diff']:+.5f} | [{v['ci_unit'][0]:+.5f}, {v['ci_unit'][1]:+.5f}] |")
L += ["", "## K4A and K4B on the primary split", "",
      "### K4A — flexible structure model vs B1", "",
      f"- Rule: {k4f['K4A']['rule']}",
      f"- ΔMAE = **{k4f['K4A']['mae_diff_vs_B1']:+.5f}**, 95% scaffold CI {k4f['K4A']['ci_unit']}",
      f"- Relative reduction: **{k4f['K4A']['rel_reduction_pct']:+.2f}%**",
      f"- **K4A pass: {k4f['K4A']['pass']}**", "",
      "### K4B — flexible structure model vs MASS FLEX", "",
      f"- Rule: {k4f['K4B']['rule']}",
      f"- ΔMAE = **{k4f['K4B']['mae_diff_vs_MASS_FLEX']:+.5f}**, 95% scaffold CI {k4f['K4B']['ci_unit']}",
      f"- Relative reduction: **{k4f['K4B']['rel_reduction_pct']:+.2f}%** "
      f"(minimum required {k4f['K4B']['min_required_rel_reduction_pct']}%)",
      f"- **K4B pass: {k4f['K4B']['pass']}**", "",
      "### Same criteria applied to the interpretable Tier A model", "",
      f"- K4A pass: **{k4a_['K4A']['pass']}** (ΔMAE {k4a_['K4A']['mae_diff_vs_B1']:+.5f}, CI {k4a_['K4A']['ci_unit']})",
      f"- K4B pass: **{k4a_['K4B']['pass']}** (ΔMAE {k4a_['K4B']['mae_diff_vs_MASS_FLEX']:+.5f}, "
      f"{k4a_['K4B']['rel_reduction_pct']:+.2f}%, CI {k4a_['K4B']['ci_unit']})", ""]
w("FLEXIBLE_PREDICTIVE_BENCHMARK.md", L)

# ===========================================================================
# NEGATIVE_CONTROLS_P2.md
# ===========================================================================
L = ["# NEGATIVE_CONTROLS_P2.md", "", HDR,
     f"Permutation replicates per control: **{ctrl['n_permutations']}**. "
     f"Primary split: **{ctrl['primary_split']}**.", "",
     "## The null decision rule was fixed before the controls ran", "",
     f"{ctrl['null_rule']}.", "",
     "This is deliberately **not** six independent α = 0.05 tests. Running six",
     "nominal tests and demanding that every individual p-value exceed 0.05",
     "would make a false alarm near-certain; the family is controlled jointly.", "",
     "Per `DEVIATIONS.md` D13 each control fixes the estimator's",
     "hyperparameters at the modal configuration chosen by the real run's inner",
     "loops and applies that frozen estimator identically to observed and",
     "permuted data. Re-tuning inside every replicate would make the null",
     "reflect search variance rather than the mechanism under test.", "",
     f"Frozen hyperparameters: `{ctrl['frozen_hyperparameters']}`.", "",
     f"Reference: B1 MAE = {ctrl['reference']['B1_mae']:.5f}, "
     f"Tier A MAE = {ctrl['reference']['TIER_A_mae']:.5f}.", "",
     "The statistic is **MAE improvement over B1**.", "",
     "## Two families, two rules", "",
     "The pre-registration wrote a single rule for all six controls. That was",
     "wrong, and `DEVIATIONS.md` **D16** records the correction. The six ask two",
     "opposite questions:", "",
     "- **Destruction controls (NC1–NC3).** Permutation is applied to the real",
     "  structure; the question is whether signal *survives destruction*. The",
     "  object under test is the **null distribution itself**. The real-data",
     "  statistic exceeding that null is the **desired** outcome — it confirms",
     "  the permutation worked — and must never be read as a failure. Fires if",
     "  the null's 95th percentile retains more than **10%** of the real",
     "  structural effect.",
     "- **Nuisance controls (NC4, NC6, NC7).** The observed statistic *is* the",
     "  nuisance predictor's own performance and must sit inside its own null.",
     "  Fires if it exceeds the null 95th percentile, with BH at q = 0.10 across",
     "  the three.", "",
     f"Real structural effect used as the destruction reference: "
     f"**{ctrl['controls']['NC1_energy_shuffle_within_compound']['real_effect_for_reference']:+.5f}** "
     f"(B1 MAE {ctrl['reference']['B1_mae']:.5f} − Tier A MAE {ctrl['reference']['TIER_A_mae']:.5f}).", "",
     "## Destruction controls", "",
     "| Control | Null mean | Null p95 | p95 as share of real effect | Limit | Fires |",
     "|---|---|---|---|---|---|"]
for n, v in ctrl["controls"].items():
    if v["family"] != "destruction":
        continue
    L.append(f"| `{n}` | {v['null_mean']:+.6f} | {v['null_p95']:+.6f} | "
             f"**{100*v['null_p95_as_share_of_real_effect']:+.1f}%** | "
             f"{100*v['limit']:.0f}% | **{v['fires']}** |")
L += ["", "All three nulls sit at or below zero: permuting energy labels,",
      "descriptors, or whole trajectories destroys the effect rather than",
      "preserving it. This is what a working pipeline looks like.", "",
      "## Nuisance controls", "",
      "| Control | Observed | Null mean | Null p95 | p | Exceeds p95 | BH q=0.10 | Fires |",
      "|---|---|---|---|---|---|---|---|"]
for n, v in ctrl["controls"].items():
    if v["family"] != "nuisance":
        continue
    L.append(f"| `{n}` | {v['observed']:+.5f} | {v['null_mean']:+.6f} | "
             f"{v['null_p95']:+.6f} | {v['p_value']} | {v['exceeds_null_p95']} | "
             f"{v.get('bh_significant_at_q0.10')} | **{v['fires']}** |")
L += ["", "## What each control tests", "",
      "| Control | What it tests |", "|---|---|",
      "| NC1 | permuting the six energy labels within a trajectory must destroy the energy signal |",
      "| NC2 | permuting descriptors across compounds must destroy structural information |",
      "| NC3 | permuting whole trajectories against descriptors must do the same, jointly |",
      "| NC4 | a uniform random variable and an alphabetical index must never predict |",
      "| NC6 | mixture identity must not predict trajectory shape (batch confounding) |",
      "| NC7 | retention time must not predict trajectory shape (co-elution confounding) |", "",
      f"**Controls fired: {ctrl['controls_fired'] or 'none'}.**", "",
      f"**Verdict: {ctrl['verdict']}.**", ""]
if ctrl["any_control_fires"]:
    f7 = ctrl["nc7_followup"]
    L += ["## NC7 fired — follow-up", "",
          "A firing control is a **BLOCKER until explained**. Phase 1 anticipated",
          "this one: `CONFOUNDERS.md` finding 4 recorded |rho| up to 0.36 between",
          "retention time and mu, and left the resolution to NC7.", "",
          f"*{f7['question']}?*", "",
          "| Model | Improvement over B1 |", "|---|---|",
          f"| Retention time alone | {f7['improvement_rt_alone']:+.5f} |",
          f"| Tier A alone | {f7['improvement_tier_a_alone']:+.5f} |",
          f"| Tier A + retention time | {f7['improvement_tier_a_plus_rt']:+.5f} |", "",
          f"RT alone recovers **{100*f7['rt_share_of_structural_effect']:.1f}%** of the structural effect — it",
          "genuinely predicts. But adding it to Tier A gains only",
          f"**{f7['incremental_gain_from_adding_rt']:+.5f}**, i.e. "
          f"{100*f7['incremental_gain_from_adding_rt']/f7['improvement_tier_a_alone']:.1f}% of the Tier A effect.", "",
          "**Structure already contains what retention time knows.** RT tracks",
          "lipophilicity, which is itself a structural property, so RT is a",
          "**structure surrogate rather than an independent confounder**, and it",
          "does not carry the structural result.", "",
          "**Status: explained.** It does not block, but it restricts: co-elution",
          "and matrix effects cannot be separated from lipophilicity with these",
          "data, so no mechanistic reading may lean on RT-correlated descriptors.", ""]
w("NEGATIVE_CONTROLS_P2.md", L)

# ===========================================================================
# PREPROCESSING_ROBUSTNESS_P2.md
# ===========================================================================
P, M, N = rob["preprocessing_robustness"], rob["mixture_confounding"], rob["negative_mode"]
L = ["# PREPROCESSING_ROBUSTNESS_P2.md", "", HDR,
     "## Scope, stated before the numbers", "",
     f"{P['scope']}", "",
     "| Quantity | Value |", "|---|---|",
     f"| Matched compounds (raw ∩ curated) | **{P['n_matched_compounds']}** |",
     f"| Curated development corpus | {P['n_curated_corpus_compounds']} |",
     f"| Coverage | **{P['coverage_pct']}%** |", "",
     "**This is subset preprocessing robustness, not full-corpus independent",
     "raw replication.** No claim of the latter is made anywhere in Phase 2, and",
     "agreement on 39 compounds is not extrapolated to 549.", "",
     "## The headline association under both branches", "",
     "rho(mu, precursor m/z), matched subset:", "",
     "| NCE | Curated | Raw mzML |", "|---|---|---|"]
for e in ["15", "30", "45", "60", "75", "90"]:
    cu = P["rho_mu_vs_precursor_mz_by_branch"]["curated"].get(e)
    rw = P["rho_mu_vs_precursor_mz_by_branch"]["raw"].get(e)
    L.append(f"| {e} | {cu} | {rw} |")
L += ["", f"Same sign at every energy: **{P['rho_agreement']['same_sign_at_every_energy']}**. "
      f"Largest absolute difference: **{P['rho_agreement']['max_abs_difference']}**.", "",
      "## mu itself, paired across branches", "",
      "| Quantity | Value |", "|---|---|",
      f"| Paired cells | {P['mu_agreement']['n_paired_cells']} |",
      f"| Median difference (raw − curated) | {P['mu_agreement']['median_difference_raw_minus_curated']:+.5f} |",
      f"| Mean absolute difference | {P['mu_agreement']['mean_abs_difference']:.5f} |",
      f"| Spearman | {P['mu_agreement']['spearman']} |",
      f"| Phase 1 inter-mixture variability (upper bound) | {P['mu_agreement']['phase1_intermixture_sd_upper_bound']} |", "",
      f"*{P['mu_agreement']['note']}.*", "",
      "## Mixture confounding and K8", "",
      f"Question: {M['question']}.", "",
      "| Model | MAE (S2) |", "|---|---|",
      f"| MASS FLEX | {M['mass_flex_mae']:.5f} |",
      f"| MASS FLEX + mixture identity | {M['mass_flex_plus_mix_mae']:.5f} |", "",
      f"Mixture gain over MASS FLEX: **{M['mix_gain_over_mass_flex']['mae_diff']:+.5f}** "
      f"(95% scaffold CI {M['mix_gain_over_mass_flex']['ci_scaffold']}); improves = "
      f"**{M['mix_gain_over_mass_flex']['improves']}**.", "",
      f"Structure gain over MASS FLEX for comparison: "
      f"**{M['structure_gain_over_mass_flex']['mae_diff']:+.5f}** "
      f"(CI {M['structure_gain_over_mass_flex']['ci_scaffold']}).", "",
      "### Leave-one-mixture-out", "",
      "| Mixture | Compounds | MASS FLEX MAE | TIER_A MAE | Δ |", "|---|---|---|---|---|"]
for m, v in M["leave_one_mixture_out"].items():
    L.append(f"| {m} | {v['n_compounds']} | {v['MASS_FLEX']:.5f} | {v['TIER_A']:.5f} | "
             f"{v['tier_a_minus_mass_flex']:+.5f} |")
L += ["", f"**K8 fires: {M['K8']['fires']}.** Rule: {M['K8']['rule']}.", "",
      "## Negative mode — bounded scope", "",
      f"{N['scope']}", "",
      f"Compounds: **{N['n_compounds']}**, rows: {N['n_rows']}.", "",
      f"**Repeatability: {N['repeatability']}**", "",
      "| Model | MAE (S2, negative mode) |", "|---|---|"]
for k, v in N["mae"].items():
    L.append(f"| {k} | {v:.5f} |")
L += ["",
      f"- K4A (Tier A vs B1): ΔMAE **{N['K4A_tier_a_vs_B1']['mae_diff']:+.5f}**, "
      f"CI {N['K4A_tier_a_vs_B1']['ci_scaffold']}, pass = **{N['K4A_tier_a_vs_B1']['pass']}**",
      f"- K4B (Tier A vs MASS FLEX): ΔMAE **{N['K4B_tier_a_vs_MASS_FLEX']['mae_diff']:+.5f}** "
      f"({N['K4B_tier_a_vs_MASS_FLEX']['rel_reduction_pct']:+.2f}%), "
      f"CI {N['K4B_tier_a_vs_MASS_FLEX']['ci_scaffold']}, pass = "
      f"**{N['K4B_tier_a_vs_MASS_FLEX']['pass']}**", "",
      "Negative mode is a qualitative replication check only. It does not",
      "double Phase 2 scope, and no claim requiring a negative-mode noise floor",
      "is made because no such estimate exists.", ""]
w("PREPROCESSING_ROBUSTNESS_P2.md", L)
print("all reports written")
