"""Generate every Phase 3 markdown report from the machine-readable artifacts.

No number in any Phase 3 report is typed by hand: each is read from
`artifacts/p3_*.json`, so the reports cannot drift from the evidence.

Writes SYNTHETIC_GENERATORS.md, SYMBOLIC_SEARCH_SPEC.md,
FALSIFICATION_HARNESS.md, NULL_CALIBRATION.md, ENGINE_VALIDATION.md,
PHASE4_FROZEN_DISCOVERY_PROTOCOL.md and artifacts/phase4_frozen_protocol.json.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
ART = ROOT / "artifacts"

from muru.discovery import equivalence, falsify, grammar, nulls, protocol  # noqa: E402
from muru.discovery.engine import GPLEARN_CONFIG, PYSR_CONFIG              # noqa: E402
from muru.synth import generators as G                                     # noqa: E402
from muru.synth import plan                                                # noqa: E402


def load(name):
    p = ART / name
    return json.loads(p.read_text()) if p.exists() else None


def prereg_header() -> str:
    sha = hashlib.sha256((ROOT / "PHASE3_PREREGISTRATION.md").read_bytes()).hexdigest()
    try:
        commit = subprocess.run(
            ["git", "log", "-1", "--format=%H", "--", "PHASE3_PREREGISTRATION.md"],
            cwd=ROOT, capture_output=True, text=True).stdout.strip()
    except Exception:
        commit = "unknown"
    return (f"Generated by `scripts/t3_50_reports.py` from machine-readable Phase 3\n"
            f"artifacts. Pre-registration: `PHASE3_PREREGISTRATION.md`\n"
            f"(sha256 `{sha}`,\ncommitted `{commit}`), frozen **before** any "
            f"governed symbolic run.\n")


def by_block(worlds):
    d = defaultdict(list)
    for w in worlds:
        if w.get("status") == "ok":
            d[w["block"]].append(w)
    return d


# --------------------------------------------------------------------------
def synthetic_generators(worlds) -> str:
    blocks = by_block(worlds)
    rows = []
    for spec_block, ws in sorted(blocks.items()):
        fams = sorted({w["family"] for w in ws})
        shas = {w["generator"]["sha256"][:12] for w in ws}
        rows.append(f"| `{spec_block}` | {', '.join(fams)} | {len(ws)} | "
                    f"{len(shas)} distinct |")

    gc = [w for w in worlds if w.get("block") == "GC" and w.get("status") == "ok"]
    gc_rows = []
    for w in sorted(gc, key=lambda w: (w["cutoff_da"], w["replicate"])):
        rho = w["generator"]["params"]["rho_mu_mass_by_energy"]
        gc_rows.append(f"| {w['cutoff_da']:.0f} Da | r{w['replicate']} | "
                       + " | ".join(f"{r:+.3f}" for r in rho) + " |")

    g4 = [w for w in worlds if w.get("block") == "G4" and w.get("status") == "ok"]
    maxcorr = max((w["generator"]["params"]["max_abs_corr_offset_descriptor"]
                   for w in g4), default=float("nan"))

    return f"""# SYNTHETIC_GENERATORS.md

{prereg_header()}
Generator version **`{G.GENERATOR_VERSION}`**, truth version
**`{worlds[0]['generator']['truth_version']}`**.

Planted equations live in `src/muru/synth/truth.py`, which **cannot appear in
the import closure of `muru.discovery`** — the code path the search runs
through. `tests/test_p3_import_graph.py` walks the real transitive closure and
plants a violation to prove the check can fail.

## Covariate source

Real-covariate, synthetic-response worlds are built on the **439 development
compounds** and the frozen energy grid {{15, 30, 45, 60, 75, 90}} NCE, so
mass-descriptor correlation, descriptor ranges, scaffold grouping and chemical
support stay realistic. **Only covariates are read.** No observed `mu` value
enters any synthetic response; `tests/test_p3_seal.py` asserts that the
generated response is not the observed one. The 110 sealed confirmation
compounds are excluded by connectivity key before any covariate is touched.

`GA` is fully synthetic and uses no real chemistry, guarding against the
possibility that recovery depends on some property of the real descriptor
matrix.

## Shared trajectory shape

`Φ(u) = 0.2414 + 0.7586 / (1 + u^1.4874)`, a logistic in log-energy, with
`mu = Φ(E / g(z))`. The three constants were calibrated **once**, before any
governed run, against the marginal `mu`-by-energy means of the development
corpus and reproduce those six means to within 0.011. They are frozen.

## Blocks built

| Block | Families | Worlds | Output hashes |
|---|---|---|---|
{chr(10).join(rows)}

## Determinism and versioning

Every world records generator version, truth version, seed, parameter set,
covariate source, planted equation, noise regime, split assignment and an
output SHA-256 over the response, the energy column, the compound keys and the
descriptor matrix. World seeds derive from
`sha256(generator_version | family | replicate | noise_regime)`, so a clean
rerun of any single world reproduces it without replaying the ones before it.
`tests/test_p3_generators.py` asserts hash equality across rebuilds and hash
inequality across replicates and noise regimes.

Generated outputs are never edited by hand.

## Noise regimes

| Regime | SD on `mu` | Rationale |
|---|---|---|
| `low` | {G.NOISE_REGIMES['low']} | below any measured variability |
| `moderate` | **{G.NOISE_REGIMES['moderate']}** | the Phase 1 conservative inter-mixture variability estimate |
| `adverse` | {G.NOISE_REGIMES['adverse']} | roughly double the upper bound |

`0.0295` is an **upper bound on technical repeatability**, not an instrument
noise floor and not pure Gaussian technical error
(`MASTER_PLAN_CLARIFICATIONS.md` C4). It is used only as a scale reference.

Missing cells are applied at the **measured** rate
{G.CELL_DROPOUT_RATE:.4f} (99.03% coverage in the real corpus), never taking a
compound below {G.MIN_ENERGIES_PER_COMPOUND} energies. The master plan's assumed
15% missingness does not describe this corpus (`DEVIATIONS_P3.md` D3).

## G4 — the pure null the K6 gate rests on

Across the {len(g4)} G4 worlds, the largest absolute correlation between the
compound-level offset and **any** descriptor is **{maxcorr:.4f}**. The null
contains no descriptor signal to find.

## GC — the Phase 2 measurement-coupling adversary

Phase 2 restriction 1 is binding. GC holds fractional fragmentation fixed as a
**law** — every compound draws fragment positions and intensities from one
common, mass-independent distribution — lets precursor mass vary, applies a
fixed absolute low-mass cutoff, and computes `mu` exactly as the real pipeline
does: `mu = SY + (1 − SY)·φ` with `φ = ⟨m/z fragment⟩ / m/z precursor`.
Per-compound realizations vary but are **independent of every descriptor**, so
any descriptor structure found here is spurious by construction.

Spearman ρ(mu, precursor m/z) by collision energy:

| Cutoff | World | 15 | 30 | 45 | 60 | 75 | 90 |
|---|---|---|---|---|---|---|---|
{chr(10).join(gc_rows)}

With **no** cutoff the same construction gives ρ numerically indistinguishable
from zero — the analytic result behind the Phase 2 audit, asserted directly in
`tests/test_p3_generators.py`.

The cutoffs are **stipulated** at three interpretable instrument settings and
were never tuned to reproduce the observed ρ = −0.676.

**Restriction, restated because it binds.** This generator tests robustness of
the discovery system. It does **not** identify the mechanism of the real
association, and it does not establish what fraction of the observed
association is artifactual. No such fraction is claimed anywhere in Phase 3.

## GRT — retention-time surrogate

A latent property drives both the descriptors and retention time; RT predicts
the response observationally but is not the planted cause. This is a bounded
stress test, not chromatography modelling, and it does **not** resolve the real
NC7 finding causally. Phase 2's wording stands: RT carries predictive signal by
itself but adds little beyond Tier A descriptors, consistent with a
structure-associated surrogate in this dataset; independent confounding cannot
be completely excluded.

## Null constructions

The {plan.N_NULL_CAL} calibration worlds cycle the four master-plan 13.6
constructions, so each contributes to the per-complexity distribution rather
than each getting a thin sample of its own:

{chr(10).join('- `' + c + '`' for c in G.NULL_CONSTRUCTIONS)}
"""


# --------------------------------------------------------------------------
def symbolic_search_spec(env, worlds) -> str:
    v = (env or {}).get("versions", {})
    stab = [w["stability"]["fraction"] for w in worlds
            if w.get("status") == "ok" and w["stability"]["n_seeds"]]
    return f"""# SYMBOLIC_SEARCH_SPEC.md

{prereg_header()}
## Engines

| Role | Engine | Version |
|---|---|---|
| Primary | **PySR** | {v.get('pysr', '?')} (SymbolicRegression.jl {v.get('SymbolicRegression_jl', '?')}, Julia {v.get('julia', '?')}) |
| Comparison arm | gplearn | {v.get('gplearn', '?')} |
| Canonicalization | SymPy | {v.get('sympy', '?')} |

PySR is the primary engine and stays primary. gplearn is a **comparison arm on
T2**, not a tournament entrant, and **cannot rescue a failing PySR
calibration**: if PySR failed K6 and gplearn passed, switching would require an
explicit documented deviation and independent recalibration, not a silent
substitution.

## Targets

| Target | What it is | Role |
|---|---|---|
| T1 | joint `(Φ, g)` collapse fit, alternating an isotonic shared `Φ` against per-compound scales | fitted for every world; its adequacy test decides H-MAIN |
| **T2** | the estimated scale `ĝ_i`, inverse-variance weighted, as a function of the 12 dimensionless Tier A descriptors | **the governed symbolic target**; every gate, threshold and false-positive count is computed on it |
| T3 | direct `mu = f(E, z)` | **not run** — the plan itself calls it diagnostic and the easiest place to overfit (`DEVIATIONS_P3.md` D2) |

`g` is identified only up to a positive multiplicative constant, so fitted
scales are normalized to unit geometric mean and every comparison is made up to
positive scaling.

## Grammar — frozen

| Item | Value |
|---|---|
| Binary | {', '.join('`' + o + '`' for o in grammar.BINARY_OPERATORS)} |
| Unary | {', '.join('`' + o + '`' for o in grammar.UNARY_OPERATORS)} |
| Excluded | `exp` (`DEVIATIONS_P3.md` D1), all trigonometric functions, free-exponent `^` |
| Maximum complexity | **{grammar.MAX_COMPLEXITY}** |
| Nested limits | `{grammar.NESTED_CONSTRAINTS}` |

### Protected numerics

{chr(10).join(f'- **{k}** — {v}' for k, v in grammar.PROTECTED_SEMANTICS.items())}

Candidate invalidity is never converted into a favourable score.
`tests/test_p3_grammar.py` plants `1/(a-a)` and `log(a-b)` and requires them to
be marked invalid rather than raising or scoring.

## Dimensional discipline

All inputs are dimensionless: energy NCE/30, mass Da/500, counts divided by
their development-corpus median, TPSA/54.5, heteroatom fraction/0.25. A
recovered law is a statement about **dimensionless** quantities and is never
reported as a physical law in raw units.

## Complexity — one metric everywhere

Node count over the parsed tree: variable 1, constant 1, binary operation 1,
unary operation 1; an integer or half-integer power is one unary operation over
its base, so `x**2` costs the same as `square(x)`. Parsing deliberately carries
no positivity assumption, which would restructure `sqrt(a*b)` into
`sqrt(a)*sqrt(b)` and count a tree the engine never searched
(`DEVIATIONS_P3.md` D7).

The same function scores candidate ranking, the Pareto front, null calibration
and the Phase 4 thresholds.

## Candidate equivalence — not string matching

1. symbolic simplification where it is safe and terminates,
2. algebraic equivalence **up to a positive multiplicative constant**,
3. dense noise-free evaluation on an independently generated
   {equivalence.N_LHC_ADJUDICATE:,}-point Latin hypercube
   ({equivalence.N_LHC_CLUSTER:,} for within-world clustering), never on
   training points,
4. variable-support comparison,
5. complexity comparison.

Tolerances: relative RMSE after optimal positive rescaling
< {equivalence.EXACT_REL_RMSE:g} ⇒ symbolic-equivalent; `r` >
{equivalence.FUNC_MIN_R} and relative RMSE < {equivalence.FUNC_REL_RMSE} ⇒
functionally equivalent. A high-complexity interpolant with tiny training error
is **not** recovery.

## Search configuration

```
{json.dumps({k: v for k, v in PYSR_CONFIG.items() if k != 'nested_constraints'}, indent=1)}
```

gplearn comparison arm: `{json.dumps(GPLEARN_CONFIG)}`, on
{len(plan.gplearn_worlds())} worlds × {plan.N_GPLEARN_SEEDS} seeds
(`DEVIATIONS_P3.md` D5).

## Seeds and stability

**{protocol.N_SEEDS} seeds per world**, frozen before any governed run and
recorded in `artifacts/p3_seed_manifest.json`. Per seed the complexity **elbow**
is taken — the smallest complexity within {protocol.ELBOW_TOL} of the best
validation R² on that seed's Pareto front. Across seeds, picks are clustered by
numerical fingerprint into expression **families**; stability is that family's
share, and the requirement is ≥ **20/30**.

Stability is never defined by identical expression strings.

Observed selection frequency across all {len(stab)} adjudicated worlds:
median **{np.median(stab):.2f}**, first quartile **{np.percentile(stab, 25):.2f}**.

## Grouped evaluation

Scaffold-group-disjoint train 60% / validation 20% / test 20%, groups filled
largest-first into the currently smallest partition — the Phase 2 rule. Whole
trajectories move together and no scaffold group straddles a boundary;
`tests/test_p3_protocol.py` asserts this and checks that one 80-compound group
cannot dominate a partition.
"""


# --------------------------------------------------------------------------
def falsification_harness(worlds) -> str:
    ok = [w for w in worlds if w.get("status") == "ok" and w.get("harness")]
    counts = defaultdict(lambda: [0, 0])
    for w in ok:
        for k, passed in w["harness"]["required_results"].items():
            counts[k][1] += 1
            counts[k][0] += bool(passed)
    rows = [f"| `{k}` | {falsify.REQUIRED.index(k) if k in falsify.REQUIRED else '-'} "
            f"| {v[0]}/{v[1]} |" for k, v in sorted(counts.items())]
    fail = defaultdict(int)
    for w in ok:
        for k in w["harness"]["failed_rungs"]:
            fail[k] += 1
    return f"""# FALSIFICATION_HARNESS.md

{prereg_header()}
F1–F12 run as an automated ladder with machine-readable pass/fail per rung. A
candidate must survive the complete **required** set. This is not a "validation
score": each rung tests a distinct way the candidate could be an artifact.

## Rung status

| Rung | Test | Status |
|---|---|---|
| F1 | reproducibility of the recorded artifact | **required** |
| F2 | invariance to a defensible change in the estimation pipeline | **required** |
| F3 | source-branch invariance | **not applicable** |
| F4 | compound holdout | **required** |
| F5 | scaffold holdout — **primary claim gate** | **required** |
| F6 | similarity-cluster holdout | **required** |
| F7 | influence robustness (top 5% dropped, leave-one-mix-out) | **required** |
| F8 | descriptor ablation, mass block removed together | **labelling** |
| F9 | energy-subset stability | **required** |
| F10 | negative controls — the candidate must FAIL on permuted targets | **required** |
| F11 | mode replication | **not applicable** |
| F12 | extrapolation probe | **supporting only** |

A rung recorded `not_applicable` is **never** counted as a pass.

**F3** has no synthetic counterpart: a synthetic response has no intensity
cutoff, no annotation filter and no raw branch. The real raw branch covers 39
compounds (7.1%) and licenses no corpus-level preprocessing-invariance claim in
any case. **F11** is not evaluable because the generators are mode-agnostic;
Phase 2's negative-mode K4B failure remains binding regardless.

**F8 labels, it does not reject.** Master plan 16.1: if removing precursor mass
destroys the result, the "law" *is* a mass law and is reported as such. F8 gates
only a claim of structure **beyond** mass, using the Phase 2 mass block
`{{{', '.join(protocol.MASS_BLOCK)}}}` removed together — dropping the named mass
variable alone would leave its proxies in place.

**F12 is never a gate.** Six energy levels cannot support an extrapolation
requirement.

## Observed rung outcomes across {len(ok)} adjudicated candidates

| Rung | Required | Passed |
|---|---|---|
{chr(10).join(rows)}

Most common failure: {', '.join(f'`{k}` ({v})' for k, v in sorted(fail.items(), key=lambda x: -x[1])[:5]) or 'none'}.

## Constant re-fitting

The collapse target identifies `g` only up to a positive multiplicative
constant, so each rung re-fits the candidate's **affine scale and offset** by
weighted least squares on the **training** partition only, then evaluates on the
holdout. That is exactly the freedom the science allows and no more.

## The harness is itself tested

`tests/test_p3_falsify.py` builds small worlds with known answers and requires
the ladder to pass the genuine relationship, reject a deliberately planted
artifact expression, reject a constant, reject a high-complexity interpolant
built from signal-free descriptors, identify mass as the carrier in a mass-only
world, and destroy the true law under permuted targets.
"""


# --------------------------------------------------------------------------
def null_calibration(cal, fp) -> str:
    thr = cal["threshold_by_complexity"]
    med = cal["median_by_complexity"]
    lo, hi = cal.get("threshold_ci_lo", []), cal.get("threshold_ci_hi", [])
    rows = [f"| {c} | {med[c]:+.4f} | **{thr[c]:+.4f}** | "
            + (f"[{lo[c]:+.4f}, {hi[c]:+.4f}] |" if lo and lo[c] is not None
               else "— |")
            for c in range(1, grammar.MAX_COMPLEXITY + 1)]
    g4 = fp["G4_pure_null"]
    k6 = fp["K6"]
    g4m = fp["G4M_mass_conditional_null"]
    return f"""# NULL_CALIBRATION.md

{prereg_header()}
Genetic programming always returns something, so a raw symbolic-regression score
means nothing on its own. The threshold a candidate must clear is built
empirically, **at its own complexity**, from worlds where no valid structural
conjecture exists.

## The statistic

**The maximum over all {cal['n_seeds_per_world']} seeds of the best validation
R² attainable at complexity ≤ c.**

Taking the max over seeds is what prices in search multiplicity: the protocol
runs the search 30 times and keeps the best, so the null is allowed the same.
A discovered expression is never compared to a naive single-model p-value.

## Design

| Item | Value |
|---|---|
| Calibration worlds | **{cal['n_worlds']}** (block `NCAL`) |
| Null constructions | {len(cal['constructions'])}, cycled across worlds |
| Seeds per world | {cal['n_seeds_per_world']} |
| Quantile | **{cal['quantile']:.0f}th percentile** |
| Monotonicity | thresholds are made non-decreasing in complexity — a larger hypothesis space cannot make chance fitting harder |
| Disjointness | {cal['disjointness']} |

## Threshold table

| Complexity | Null median | **95th percentile threshold** | 95% bootstrap interval on the threshold |
|---|---|---|---|
{chr(10).join(rows)}

This table is **frozen for Phase 4**.

### The gap between the median and the threshold is the whole point

At complexity {grammar.MAX_COMPLEXITY} the null **median** best-of-30-seeds R² is
{med[grammar.MAX_COMPLEXITY]:+.4f} — indistinguishable from zero, which is what a
null should give. The **95th percentile** is
{thr[grammar.MAX_COMPLEXITY]:+.4f}. In other words, in a world where no
descriptor-level relationship exists at all, the best of thirty symbolic
searches reaches R² ≈ {thr[grammar.MAX_COMPLEXITY]:.2f} by chance alone.

A candidate compared against a naive single-model null would clear that bar
easily and be reported as a discovery. This is precisely the failure the
master plan's §13.6 calibration exists to prevent, and it is why the threshold
is built from the max-over-seeds statistic rather than a per-run p-value.

### The threshold's own uncertainty

{cal.get('threshold_ci_note', '')}. The intervals above are wide — at complexity
{grammar.MAX_COMPLEXITY} the threshold is {thr[grammar.MAX_COMPLEXITY]:+.4f} with
interval [{lo[grammar.MAX_COMPLEXITY]:+.4f}, {hi[grammar.MAX_COMPLEXITY]:+.4f}] —
because a 95th percentile estimated from {cal['n_worlds']} worlds rests on its
top two or three. The point estimate is used as the frozen gate, as
pre-registered; the interval is reported so the table is not read as more
precise than it is, and it is carried forward as a Phase 4 restriction.

## Per-construction check

| Construction | Worlds | p95 at c=10 | p95 at c=20 |
|---|---|---|---|
{chr(10).join(f"| `{c}` | {d['n_worlds']} | {d['p95_by_complexity'][10]:+.4f} | {d['p95_by_complexity'][20]:+.4f} |" for c, d in sorted(cal['per_construction'].items()))}

Reported separately so a single pathological construction is visible rather than
buried in the pooled quantile.

## G4 false-positive experiment

Each of the {g4['n_valid_replicates']} G4 replicates ran the frozen 30-seed
search, the frozen ranking rule and the complete falsification harness.

```
false-positive rate = {g4['n_accepted']} / {g4['n_valid_replicates']} = {g4['rate']:.4f}
```

| Quantity | Value |
|---|---|
| Numerator (null worlds producing an accepted conjecture) | **{g4['n_accepted']}** |
| Denominator (valid null replicates) | **{g4['n_valid_replicates']}** |
| Rate | **{g4['rate']:.4f}** |
| {g4['ci_method']} 95% interval | **[{g4['ci'][0]:.4f}, {g4['ci'][1]:.4f}]** |

{g4['note']}. `p = 0` language is not used for a finite simulation count: with
{g4['n_valid_replicates']} replicates the interval, not the point estimate, is
the claim.

## K6

| Item | Value |
|---|---|
| Criterion | {k6['criterion']} |
| Observed | **{k6['observed_rate']:.4f}** ({k6['n_accepted']}/{k6['n_valid_replicates']}) |
| 95% interval | [{k6['ci'][0]:.4f}, {k6['ci'][1]:.4f}] |
| **Verdict** | **{k6['verdict']}** |

{k6['uncertainty_note']}.

## G4M — mass-conditional null (supplementary)

The master plan's G4 is a pure null. G4M additionally makes the **mass**
dependence real while leaving no non-mass structure, which is the null matched
to the actual Phase 2 question — structure beyond energy **and mass**.

| Quantity | Value |
|---|---|
| Worlds | {g4m['n_worlds']} |
| Accepted (any candidate) | {g4m['n_accepted_any']} |
| **Accepted claiming structure beyond mass** | **{g4m['n_accepted_claiming_structure_beyond_mass']}** |
{f"| Rate | {g4m['rate_structure_beyond_mass']['rate']:.4f}, 95% CI [{g4m['rate_structure_beyond_mass']['ci'][0]:.4f}, {g4m['rate_structure_beyond_mass']['ci'][1]:.4f}] |" if g4m.get('rate_structure_beyond_mass') else ''}

{g4m['note']}. K6 is adjudicated on G4, as the master plan specifies; G4M is
reported alongside, not instead.
"""


# --------------------------------------------------------------------------
def engine_validation(env) -> str:
    v, s, d = env["versions"], env["smoke_test"], env["determinism"]
    c, o = env["checkpointability"], env["operators_and_complexity"]
    return f"""# ENGINE_VALIDATION.md

{prereg_header()}
Master plan 10: verify installation, the Julia runtime, deterministic seeding as
far as the library permits, checkpointability, operator definitions, complexity
scoring, and a trivial smoke test on a known synthetic equation.

**Successful installation is not scientific validation.** This file records only
that the engine does what the protocol assumes it does.

## Environment

| Component | Version |
|---|---|
| PySR | **{v.get('pysr')}** |
| SymbolicRegression.jl | {v.get('SymbolicRegression_jl')} |
| Julia | {v.get('julia')} |
| gplearn | {v.get('gplearn')} |
| SymPy | {v.get('sympy')} |
| NumPy / pandas | {v.get('numpy')} / {v.get('pandas')} |
| scikit-learn / SciPy | {v.get('scikit_learn')} / {v.get('scipy')} |
| Python | {v.get('python')} |
| Platform | {v.get('platform')}, {v.get('cpu_count')} cores |

## Smoke test

Planted: `{s['planted']}` on clean data.

| Quantity | Value |
|---|---|
| Pareto front size | {s['n_pareto']} |
| Wall time | {s['seconds']} s |
| **Recovered** | **{s['recovered']}** |
| Recovered expression | `{s['recovered_expr']}` |
| Recovered complexity | {s['recovered_complexity']} |
| Symbolically equivalent | {s['exact_equivalent']} |
| Best validation R² on the front | {s['best_valid_r2']:.6f} |

## Determinism

| Check | Result |
|---|---|
| Two runs at the same seed produce an identical Pareto front | **{d['same_seed_identical']}** |
| Equations on that front | {d['same_seed_n_equations']} |
| A different seed produces a different front | {d['different_seed_differs']} |

{d['note']}.

## Operator and complexity definitions

Binary {o['binary_operators']}, unary {o['unary_operators']}, maximum complexity
{o['max_complexity']}. Excluded: {', '.join(o['excluded'])}.

Complexity worked examples, showing the two engines share one scale:

| Expression | Complexity |
|---|---|
{chr(10).join(f"| `{k}` | {v} |" for k, v in o['complexity_examples'].items())}

## Checkpointability

| Property | Result |
|---|---|
| Unit | `{c['unit']}` |
| Resume skips completed units | {c['resume_skips_completed']} |
| Resume advances to the next incomplete unit | {c['resume_advances']} |
| A truncated file counts as incomplete, not as a result | {c['truncated_file_treated_as_incomplete']} |
| Write | {c['atomic_write']} |

{env['disclaimer']}.
"""


# --------------------------------------------------------------------------
def frozen_protocol(cal, worlds) -> tuple[str, dict]:
    obj = {
        "protocol_version": protocol.PROTOCOL_VERSION,
        "purpose": ("frozen handoff for Phase 4 real-data symbolic discovery; "
                    "NOT executed on the real response during Phase 3"),
        "engine": {"primary": "pysr", "config": PYSR_CONFIG,
                   "comparison_arm": {"engine": "gplearn",
                                      "config": GPLEARN_CONFIG,
                                      "role": "comparison only; cannot rescue a "
                                              "failing primary calibration"}},
        "grammar": {"binary": grammar.BINARY_OPERATORS,
                    "unary": grammar.UNARY_OPERATORS,
                    "excluded": ["exp", "trigonometric", "free-exponent ^"],
                    "max_complexity": grammar.MAX_COMPLEXITY,
                    "nested_constraints": grammar.NESTED_CONSTRAINTS,
                    "protected_semantics": grammar.PROTECTED_SEMANTICS,
                    "max_invalid_fraction": grammar.MAX_INVALID_FRACTION},
        "constants": {"engine_inner_optimizer": True,
                      "final_refit": "weighted least squares, affine, TRAINING "
                                     "partition only"},
        "feature_transformations": {"dimensionless_scale": protocol.SCALE,
                                    "energy_scale": 30.0,
                                    "note": "recovered laws are statements about "
                                            "dimensionless quantities"},
        "complexity_metric": {
            "definition": "node count over the parsed tree; variable 1, constant "
                          "1, binary op 1, unary op 1; integer/half-integer power "
                          "= one unary op over its base",
            "implementation": "muru.discovery.grammar.complexity",
            "parse_assumptions": "none; positivity is not asserted at parse time"},
        "search_budget": {"niterations": PYSR_CONFIG["niterations"],
                          "populations": PYSR_CONFIG["populations"],
                          "population_size": PYSR_CONFIG["population_size"]},
        "seed_schedule": {"n_seeds": protocol.N_SEEDS,
                          "seed_base": protocol.SEED_BASE,
                          "derivation": "SEED_BASE + sha256(world_id)[:3]*100 + k"},
        "candidate_ranking": {"per_seed": "complexity elbow",
                              "elbow_tolerance": protocol.ELBOW_TOL,
                              "across_seeds": "cluster per-seed picks by numerical "
                                              "fingerprint into families; take the "
                                              "lowest-complexity member of the "
                                              "largest family",
                              "tie_breaking": ["lower complexity",
                                               "higher validation R^2",
                                               "lexicographic expression string"]},
        "equivalence": {"hierarchy": ["symbolic simplification",
                                      "algebraic equivalence up to positive scale",
                                      "dense LHC numerical fingerprint",
                                      "variable support", "complexity"],
                        "n_lhc_adjudicate": equivalence.N_LHC_ADJUDICATE,
                        "n_lhc_cluster": equivalence.N_LHC_CLUSTER,
                        "exact_rel_rmse": equivalence.EXACT_REL_RMSE,
                        "functional_rel_rmse": equivalence.FUNC_REL_RMSE,
                        "functional_min_r": equivalence.FUNC_MIN_R},
        "null_threshold_by_complexity": cal["threshold_by_complexity"],
        "null_statistic": cal["statistic"],
        "null_calibration_worlds": cal["n_worlds"],
        "stability_requirement": {"min_selection_fraction":
                                  protocol.MIN_SELECTION_FRACTION,
                                  "expressed_as": "20 of 30 seeds",
                                  "basis": "expression families, never identical "
                                           "strings"},
        "falsification": {"required": list(falsify.REQUIRED),
                          "labelling": list(falsify.LABELLING),
                          "not_applicable_in_phase3": list(falsify.NOT_APPLICABLE),
                          "supporting_only": list(falsify.SUPPORTING),
                          "phase4_note": "F2 and F3 become evaluable on real data "
                                         "and are REQUIRED in Phase 4; F11 "
                                         "(negative mode) narrows the declared "
                                         "domain and does not reject",
                          "n_permutations_F10": falsify.N_PERMUTATIONS_F10,
                          "influence_drop_fraction":
                              falsify.INFLUENCE_DROP_FRACTION},
        "acceptance_rule": [
            "validation R^2 exceeds the null threshold at the candidate's own complexity",
            "selection frequency >= 20/30 seeds",
            "complexity <= 20",
            "invalid fraction <= 0.005",
            "the complete required falsification set passes"],
        "structural_claim_rule": [
            "variable support contains a non-mass descriptor",
            "ablating the non-mass descriptors destroys the result",
            "the mass block alone does not reproduce the result"],
        "mass_block": list(protocol.MASS_BLOCK),
        "max_candidates_advancing": 1,
        "max_candidates_note": ("one candidate per target advances: the "
                                "lowest-complexity member of the largest "
                                "expression family"),
        "stopping_rule": ("the search stops at the frozen budget; no adaptive "
                          "extension is permitted on seeing results"),
        "phase4_restrictions": [
            "positive mode only — Phase 2's structure-beyond-mass result does "
            "not replicate in negative mode (K4B FAIL, +1.93%, CI spans zero)",
            "no mechanistic reading may lean on RT-correlated descriptors (NC7)",
            "no full-corpus preprocessing-invariance claim is available (39 "
            "compounds, 7.1%)",
            "a mass-associated candidate must be reported as a mass law unless "
            "the structural-claim rule is satisfied",
            "thresholds frozen here are binding; a genuinely invalid rule must "
            "be handled as a documented deviation with conservative "
            "interpretation, not silently replaced"],
        "not_executed_in_phase3": True,
    }
    md = f"""# PHASE4_FROZEN_DISCOVERY_PROTOCOL.md

{prereg_header()}
This is a **handoff artifact**. It was frozen at Phase 3 completion and was
**not executed on the real response during Phase 3**.
`tests/test_p3_phase_boundary.py` asserts that the Phase 4 entry point refuses
to run and that no Phase 3 script references the real response corpus.

Machine-readable companion: `artifacts/phase4_frozen_protocol.json`.

## Why these thresholds are binding

Phase 3 exists partly to prevent Phase 4 from becoming an exercise in changing
rules until an attractive equation survives. The thresholds below were
calibrated on {cal['n_worlds']} null worlds **before** any real-data search
exists. If Phase 4 discovers that a frozen rule is genuinely invalid, that must
be handled as a documented deviation with **conservative** interpretation — not
by substituting a rule that happens to admit the candidate in hand.

## Grammar and complexity

Binary {', '.join('`' + o + '`' for o in grammar.BINARY_OPERATORS)}; unary
{', '.join('`' + o + '`' for o in grammar.UNARY_OPERATORS)}; `exp`,
trigonometric functions and free-exponent `^` excluded; maximum complexity
**{grammar.MAX_COMPLEXITY}**. Phase 4 may **not widen the grammar** without
recalibrating the null thresholds — a larger hypothesis space invalidates the
table below.

Complexity: node count over the parsed tree, `muru.discovery.grammar.complexity`.

## Null thresholds by complexity — frozen

| c | threshold | c | threshold |
|---|---|---|---|
{chr(10).join(f"| {c} | {cal['threshold_by_complexity'][c]:+.4f} | {c + 10} | {cal['threshold_by_complexity'][c + 10]:+.4f} |" for c in range(1, 11))}

Statistic: {cal['statistic']}.

## Acceptance rule

{chr(10).join(f'{i}. {r}' for i, r in enumerate(obj['acceptance_rule'], 1))}

A candidate additionally **claims structure beyond mass** only if:

{chr(10).join(f'{i}. {r}' for i, r in enumerate(obj['structural_claim_rule'], 1))}

## Candidate flow

| Item | Value |
|---|---|
| Seeds | {protocol.N_SEEDS} |
| Per-seed pick | complexity elbow, tolerance {protocol.ELBOW_TOL} |
| Across seeds | largest expression family by numerical fingerprint |
| Stability requirement | ≥ 20/30 |
| Tie-breaking | {', '.join(obj['candidate_ranking']['tie_breaking'])} |
| **Maximum candidates advancing** | **{obj['max_candidates_advancing']}** |
| Stopping rule | {obj['stopping_rule']} |

## Falsification requirements in Phase 4

Required in Phase 3 and Phase 4: {', '.join('`' + r + '`' for r in falsify.REQUIRED)}.
**F2 and F3 become evaluable on real data and are REQUIRED in Phase 4** — the
preprocessing grid and the raw mzML branch exist there. F8 remains a labelling
rung that gates only a structural claim. F11 narrows the declared domain rather
than rejecting. F12 remains supporting evidence.

## Binding Phase 4 restrictions

{chr(10).join('- ' + r for r in obj['phase4_restrictions'])}
"""
    return md, obj


# --------------------------------------------------------------------------
def main() -> int:
    worlds = load("p3_worlds.json") or []
    cal = load("p3_null_calibration.json")
    fp = load("p3_false_positives.json")
    env = load("p3_engine_validation.json")

    written = []
    if worlds:
        (ROOT / "SYNTHETIC_GENERATORS.md").write_text(synthetic_generators(worlds))
        (ROOT / "FALSIFICATION_HARNESS.md").write_text(falsification_harness(worlds))
        written += ["SYNTHETIC_GENERATORS.md", "FALSIFICATION_HARNESS.md"]
    if env:
        (ROOT / "ENGINE_VALIDATION.md").write_text(engine_validation(env))
        written.append("ENGINE_VALIDATION.md")
    if env and worlds:
        (ROOT / "SYMBOLIC_SEARCH_SPEC.md").write_text(symbolic_search_spec(env, worlds))
        written.append("SYMBOLIC_SEARCH_SPEC.md")
    if cal and fp:
        (ROOT / "NULL_CALIBRATION.md").write_text(null_calibration(cal, fp))
        written.append("NULL_CALIBRATION.md")
    if cal:
        md, obj = frozen_protocol(cal, worlds)
        (ROOT / "PHASE4_FROZEN_DISCOVERY_PROTOCOL.md").write_text(md)
        (ART / "phase4_frozen_protocol.json").write_text(json.dumps(obj, indent=1))
        written += ["PHASE4_FROZEN_DISCOVERY_PROTOCOL.md",
                    "artifacts/phase4_frozen_protocol.json"]
    print("[t3_50] wrote " + ", ".join(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
